// Code generated by ent, DO NOT EDIT.

package providerquota

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/drivebase/drivebase/internal/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldLTE(FieldID, id))
}

// ProviderID applies equality check predicate on the "provider_id" field. It's identical to ProviderIDEQ.
func ProviderID(v uuid.UUID) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldEQ(FieldProviderID, v))
}

// TotalBytes applies equality check predicate on the "total_bytes" field. It's identical to TotalBytesEQ.
func TotalBytes(v int64) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldEQ(FieldTotalBytes, v))
}

// UsedBytes applies equality check predicate on the "used_bytes" field. It's identical to UsedBytesEQ.
func UsedBytes(v int64) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldEQ(FieldUsedBytes, v))
}

// FreeBytes applies equality check predicate on the "free_bytes" field. It's identical to FreeBytesEQ.
func FreeBytes(v int64) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldEQ(FieldFreeBytes, v))
}

// TrashBytes applies equality check predicate on the "trash_bytes" field. It's identical to TrashBytesEQ.
func TrashBytes(v int64) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldEQ(FieldTrashBytes, v))
}

// PlanName applies equality check predicate on the "plan_name" field. It's identical to PlanNameEQ.
func PlanName(v string) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldEQ(FieldPlanName, v))
}

// SyncedAt applies equality check predicate on the "synced_at" field. It's identical to SyncedAtEQ.
func SyncedAt(v time.Time) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldEQ(FieldSyncedAt, v))
}

// ProviderIDEQ applies the EQ predicate on the "provider_id" field.
func ProviderIDEQ(v uuid.UUID) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldEQ(FieldProviderID, v))
}

// ProviderIDNEQ applies the NEQ predicate on the "provider_id" field.
func ProviderIDNEQ(v uuid.UUID) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldNEQ(FieldProviderID, v))
}

// ProviderIDIn applies the In predicate on the "provider_id" field.
func ProviderIDIn(vs ...uuid.UUID) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldIn(FieldProviderID, vs...))
}

// ProviderIDNotIn applies the NotIn predicate on the "provider_id" field.
func ProviderIDNotIn(vs ...uuid.UUID) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldNotIn(FieldProviderID, vs...))
}

// TotalBytesEQ applies the EQ predicate on the "total_bytes" field.
func TotalBytesEQ(v int64) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldEQ(FieldTotalBytes, v))
}

// TotalBytesNEQ applies the NEQ predicate on the "total_bytes" field.
func TotalBytesNEQ(v int64) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldNEQ(FieldTotalBytes, v))
}

// TotalBytesIn applies the In predicate on the "total_bytes" field.
func TotalBytesIn(vs ...int64) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldIn(FieldTotalBytes, vs...))
}

// TotalBytesNotIn applies the NotIn predicate on the "total_bytes" field.
func TotalBytesNotIn(vs ...int64) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldNotIn(FieldTotalBytes, vs...))
}

// TotalBytesGT applies the GT predicate on the "total_bytes" field.
func TotalBytesGT(v int64) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldGT(FieldTotalBytes, v))
}

// TotalBytesGTE applies the GTE predicate on the "total_bytes" field.
func TotalBytesGTE(v int64) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldGTE(FieldTotalBytes, v))
}

// TotalBytesLT applies the LT predicate on the "total_bytes" field.
func TotalBytesLT(v int64) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldLT(FieldTotalBytes, v))
}

// TotalBytesLTE applies the LTE predicate on the "total_bytes" field.
func TotalBytesLTE(v int64) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldLTE(FieldTotalBytes, v))
}

// UsedBytesEQ applies the EQ predicate on the "used_bytes" field.
func UsedBytesEQ(v int64) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldEQ(FieldUsedBytes, v))
}

// UsedBytesNEQ applies the NEQ predicate on the "used_bytes" field.
func UsedBytesNEQ(v int64) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldNEQ(FieldUsedBytes, v))
}

// UsedBytesIn applies the In predicate on the "used_bytes" field.
func UsedBytesIn(vs ...int64) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldIn(FieldUsedBytes, vs...))
}

// UsedBytesNotIn applies the NotIn predicate on the "used_bytes" field.
func UsedBytesNotIn(vs ...int64) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldNotIn(FieldUsedBytes, vs...))
}

// UsedBytesGT applies the GT predicate on the "used_bytes" field.
func UsedBytesGT(v int64) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldGT(FieldUsedBytes, v))
}

// UsedBytesGTE applies the GTE predicate on the "used_bytes" field.
func UsedBytesGTE(v int64) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldGTE(FieldUsedBytes, v))
}

// UsedBytesLT applies the LT predicate on the "used_bytes" field.
func UsedBytesLT(v int64) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldLT(FieldUsedBytes, v))
}

// UsedBytesLTE applies the LTE predicate on the "used_bytes" field.
func UsedBytesLTE(v int64) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldLTE(FieldUsedBytes, v))
}

// FreeBytesEQ applies the EQ predicate on the "free_bytes" field.
func FreeBytesEQ(v int64) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldEQ(FieldFreeBytes, v))
}

// FreeBytesNEQ applies the NEQ predicate on the "free_bytes" field.
func FreeBytesNEQ(v int64) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldNEQ(FieldFreeBytes, v))
}

// FreeBytesIn applies the In predicate on the "free_bytes" field.
func FreeBytesIn(vs ...int64) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldIn(FieldFreeBytes, vs...))
}

// FreeBytesNotIn applies the NotIn predicate on the "free_bytes" field.
func FreeBytesNotIn(vs ...int64) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldNotIn(FieldFreeBytes, vs...))
}

// FreeBytesGT applies the GT predicate on the "free_bytes" field.
func FreeBytesGT(v int64) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldGT(FieldFreeBytes, v))
}

// FreeBytesGTE applies the GTE predicate on the "free_bytes" field.
func FreeBytesGTE(v int64) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldGTE(FieldFreeBytes, v))
}

// FreeBytesLT applies the LT predicate on the "free_bytes" field.
func FreeBytesLT(v int64) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldLT(FieldFreeBytes, v))
}

// FreeBytesLTE applies the LTE predicate on the "free_bytes" field.
func FreeBytesLTE(v int64) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldLTE(FieldFreeBytes, v))
}

// TrashBytesEQ applies the EQ predicate on the "trash_bytes" field.
func TrashBytesEQ(v int64) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldEQ(FieldTrashBytes, v))
}

// TrashBytesNEQ applies the NEQ predicate on the "trash_bytes" field.
func TrashBytesNEQ(v int64) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldNEQ(FieldTrashBytes, v))
}

// TrashBytesIn applies the In predicate on the "trash_bytes" field.
func TrashBytesIn(vs ...int64) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldIn(FieldTrashBytes, vs...))
}

// TrashBytesNotIn applies the NotIn predicate on the "trash_bytes" field.
func TrashBytesNotIn(vs ...int64) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldNotIn(FieldTrashBytes, vs...))
}

// TrashBytesGT applies the GT predicate on the "trash_bytes" field.
func TrashBytesGT(v int64) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldGT(FieldTrashBytes, v))
}

// TrashBytesGTE applies the GTE predicate on the "trash_bytes" field.
func TrashBytesGTE(v int64) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldGTE(FieldTrashBytes, v))
}

// TrashBytesLT applies the LT predicate on the "trash_bytes" field.
func TrashBytesLT(v int64) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldLT(FieldTrashBytes, v))
}

// TrashBytesLTE applies the LTE predicate on the "trash_bytes" field.
func TrashBytesLTE(v int64) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldLTE(FieldTrashBytes, v))
}

// PlanNameEQ applies the EQ predicate on the "plan_name" field.
func PlanNameEQ(v string) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldEQ(FieldPlanName, v))
}

// PlanNameNEQ applies the NEQ predicate on the "plan_name" field.
func PlanNameNEQ(v string) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldNEQ(FieldPlanName, v))
}

// PlanNameIn applies the In predicate on the "plan_name" field.
func PlanNameIn(vs ...string) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldIn(FieldPlanName, vs...))
}

// PlanNameNotIn applies the NotIn predicate on the "plan_name" field.
func PlanNameNotIn(vs ...string) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldNotIn(FieldPlanName, vs...))
}

// PlanNameGT applies the GT predicate on the "plan_name" field.
func PlanNameGT(v string) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldGT(FieldPlanName, v))
}

// PlanNameGTE applies the GTE predicate on the "plan_name" field.
func PlanNameGTE(v string) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldGTE(FieldPlanName, v))
}

// PlanNameLT applies the LT predicate on the "plan_name" field.
func PlanNameLT(v string) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldLT(FieldPlanName, v))
}

// PlanNameLTE applies the LTE predicate on the "plan_name" field.
func PlanNameLTE(v string) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldLTE(FieldPlanName, v))
}

// PlanNameContains applies the Contains predicate on the "plan_name" field.
func PlanNameContains(v string) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldContains(FieldPlanName, v))
}

// PlanNameHasPrefix applies the HasPrefix predicate on the "plan_name" field.
func PlanNameHasPrefix(v string) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldHasPrefix(FieldPlanName, v))
}

// PlanNameHasSuffix applies the HasSuffix predicate on the "plan_name" field.
func PlanNameHasSuffix(v string) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldHasSuffix(FieldPlanName, v))
}

// PlanNameIsNil applies the IsNil predicate on the "plan_name" field.
func PlanNameIsNil() predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldIsNull(FieldPlanName))
}

// PlanNameNotNil applies the NotNil predicate on the "plan_name" field.
func PlanNameNotNil() predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldNotNull(FieldPlanName))
}

// PlanNameEqualFold applies the EqualFold predicate on the "plan_name" field.
func PlanNameEqualFold(v string) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldEqualFold(FieldPlanName, v))
}

// PlanNameContainsFold applies the ContainsFold predicate on the "plan_name" field.
func PlanNameContainsFold(v string) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldContainsFold(FieldPlanName, v))
}

// ExtraIsNil applies the IsNil predicate on the "extra" field.
func ExtraIsNil() predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldIsNull(FieldExtra))
}

// ExtraNotNil applies the NotNil predicate on the "extra" field.
func ExtraNotNil() predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldNotNull(FieldExtra))
}

// SyncedAtEQ applies the EQ predicate on the "synced_at" field.
func SyncedAtEQ(v time.Time) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldEQ(FieldSyncedAt, v))
}

// SyncedAtNEQ applies the NEQ predicate on the "synced_at" field.
func SyncedAtNEQ(v time.Time) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldNEQ(FieldSyncedAt, v))
}

// SyncedAtIn applies the In predicate on the "synced_at" field.
func SyncedAtIn(vs ...time.Time) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldIn(FieldSyncedAt, vs...))
}

// SyncedAtNotIn applies the NotIn predicate on the "synced_at" field.
func SyncedAtNotIn(vs ...time.Time) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldNotIn(FieldSyncedAt, vs...))
}

// SyncedAtGT applies the GT predicate on the "synced_at" field.
func SyncedAtGT(v time.Time) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldGT(FieldSyncedAt, v))
}

// SyncedAtGTE applies the GTE predicate on the "synced_at" field.
func SyncedAtGTE(v time.Time) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldGTE(FieldSyncedAt, v))
}

// SyncedAtLT applies the LT predicate on the "synced_at" field.
func SyncedAtLT(v time.Time) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldLT(FieldSyncedAt, v))
}

// SyncedAtLTE applies the LTE predicate on the "synced_at" field.
func SyncedAtLTE(v time.Time) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.FieldLTE(FieldSyncedAt, v))
}

// HasProvider applies the HasEdge predicate on the "provider" edge.
func HasProvider() predicate.ProviderQuota {
	return predicate.ProviderQuota(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, ProviderTable, ProviderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProviderWith applies the HasEdge predicate on the "provider" edge with a given conditions (other predicates).
func HasProviderWith(preds ...predicate.Provider) predicate.ProviderQuota {
	return predicate.ProviderQuota(func(s *sql.Selector) {
		step := newProviderStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProviderQuota) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProviderQuota) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProviderQuota) predicate.ProviderQuota {
	return predicate.ProviderQuota(sql.NotPredicates(p))
}
