services:
  xile-postgres:
    image: postgres:17-alpine
    container_name: xile-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: xile-local-pwd
      POSTGRES_USER: xile-local
      POSTGRES_DB: xile-db-local
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - xile-network

volumes:
  postgres-volume:
    external: false

networks:
  xile-network:
    external: false
