version: '3'

services:
  drivebase:
    image: ghcr.io/drivebase/drivebase:latest
    container_name: drivebase
    restart: always
    ports:
      - 3000:3000
    networks:
      - drivebase-network
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - NODE_ENV=production
      - PORT=3000

  postgres:
    image: postgres:17-alpine
    container_name: drivebase-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - drivebase-network

volumes:
  postgres-volume:
    external: false

networks:
  drivebase-network:
    external: false
