services:
  drivebase-postgres:
    image: postgres:17-alpine
    container_name: drivebase-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: drivebase-local-pwd
      POSTGRES_USER: drivebase-local
      POSTGRES_DB: drivebase-db-local
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - drivebase-network

volumes:
  postgres-volume:
    external: false

networks:
  drivebase-network:
    external: false
