// Code generated by ent, DO NOT EDIT.

package uploadbatch

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/drivebase/drivebase/internal/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldEQ(FieldUserID, v))
}

// ProviderID applies equality check predicate on the "provider_id" field. It's identical to ProviderIDEQ.
func ProviderID(v uuid.UUID) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldEQ(FieldProviderID, v))
}

// ParentRemoteID applies equality check predicate on the "parent_remote_id" field. It's identical to ParentRemoteIDEQ.
func ParentRemoteID(v string) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldEQ(FieldParentRemoteID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldEQ(FieldStatus, v))
}

// TotalFiles applies equality check predicate on the "total_files" field. It's identical to TotalFilesEQ.
func TotalFiles(v int) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldEQ(FieldTotalFiles, v))
}

// CompletedFiles applies equality check predicate on the "completed_files" field. It's identical to CompletedFilesEQ.
func CompletedFiles(v int) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldEQ(FieldCompletedFiles, v))
}

// FailedFiles applies equality check predicate on the "failed_files" field. It's identical to FailedFilesEQ.
func FailedFiles(v int) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldEQ(FieldFailedFiles, v))
}

// TotalBytes applies equality check predicate on the "total_bytes" field. It's identical to TotalBytesEQ.
func TotalBytes(v int64) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldEQ(FieldTotalBytes, v))
}

// TransferredBytes applies equality check predicate on the "transferred_bytes" field. It's identical to TransferredBytesEQ.
func TransferredBytes(v int64) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldEQ(FieldTransferredBytes, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldEQ(FieldCreatedAt, v))
}

// CompletedAt applies equality check predicate on the "completed_at" field. It's identical to CompletedAtEQ.
func CompletedAt(v time.Time) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldEQ(FieldCompletedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldNotIn(FieldUserID, vs...))
}

// ProviderIDEQ applies the EQ predicate on the "provider_id" field.
func ProviderIDEQ(v uuid.UUID) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldEQ(FieldProviderID, v))
}

// ProviderIDNEQ applies the NEQ predicate on the "provider_id" field.
func ProviderIDNEQ(v uuid.UUID) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldNEQ(FieldProviderID, v))
}

// ProviderIDIn applies the In predicate on the "provider_id" field.
func ProviderIDIn(vs ...uuid.UUID) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldIn(FieldProviderID, vs...))
}

// ProviderIDNotIn applies the NotIn predicate on the "provider_id" field.
func ProviderIDNotIn(vs ...uuid.UUID) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldNotIn(FieldProviderID, vs...))
}

// ProviderIDGT applies the GT predicate on the "provider_id" field.
func ProviderIDGT(v uuid.UUID) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldGT(FieldProviderID, v))
}

// ProviderIDGTE applies the GTE predicate on the "provider_id" field.
func ProviderIDGTE(v uuid.UUID) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldGTE(FieldProviderID, v))
}

// ProviderIDLT applies the LT predicate on the "provider_id" field.
func ProviderIDLT(v uuid.UUID) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldLT(FieldProviderID, v))
}

// ProviderIDLTE applies the LTE predicate on the "provider_id" field.
func ProviderIDLTE(v uuid.UUID) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldLTE(FieldProviderID, v))
}

// ParentRemoteIDEQ applies the EQ predicate on the "parent_remote_id" field.
func ParentRemoteIDEQ(v string) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldEQ(FieldParentRemoteID, v))
}

// ParentRemoteIDNEQ applies the NEQ predicate on the "parent_remote_id" field.
func ParentRemoteIDNEQ(v string) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldNEQ(FieldParentRemoteID, v))
}

// ParentRemoteIDIn applies the In predicate on the "parent_remote_id" field.
func ParentRemoteIDIn(vs ...string) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldIn(FieldParentRemoteID, vs...))
}

// ParentRemoteIDNotIn applies the NotIn predicate on the "parent_remote_id" field.
func ParentRemoteIDNotIn(vs ...string) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldNotIn(FieldParentRemoteID, vs...))
}

// ParentRemoteIDGT applies the GT predicate on the "parent_remote_id" field.
func ParentRemoteIDGT(v string) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldGT(FieldParentRemoteID, v))
}

// ParentRemoteIDGTE applies the GTE predicate on the "parent_remote_id" field.
func ParentRemoteIDGTE(v string) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldGTE(FieldParentRemoteID, v))
}

// ParentRemoteIDLT applies the LT predicate on the "parent_remote_id" field.
func ParentRemoteIDLT(v string) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldLT(FieldParentRemoteID, v))
}

// ParentRemoteIDLTE applies the LTE predicate on the "parent_remote_id" field.
func ParentRemoteIDLTE(v string) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldLTE(FieldParentRemoteID, v))
}

// ParentRemoteIDContains applies the Contains predicate on the "parent_remote_id" field.
func ParentRemoteIDContains(v string) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldContains(FieldParentRemoteID, v))
}

// ParentRemoteIDHasPrefix applies the HasPrefix predicate on the "parent_remote_id" field.
func ParentRemoteIDHasPrefix(v string) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldHasPrefix(FieldParentRemoteID, v))
}

// ParentRemoteIDHasSuffix applies the HasSuffix predicate on the "parent_remote_id" field.
func ParentRemoteIDHasSuffix(v string) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldHasSuffix(FieldParentRemoteID, v))
}

// ParentRemoteIDIsNil applies the IsNil predicate on the "parent_remote_id" field.
func ParentRemoteIDIsNil() predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldIsNull(FieldParentRemoteID))
}

// ParentRemoteIDNotNil applies the NotNil predicate on the "parent_remote_id" field.
func ParentRemoteIDNotNil() predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldNotNull(FieldParentRemoteID))
}

// ParentRemoteIDEqualFold applies the EqualFold predicate on the "parent_remote_id" field.
func ParentRemoteIDEqualFold(v string) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldEqualFold(FieldParentRemoteID, v))
}

// ParentRemoteIDContainsFold applies the ContainsFold predicate on the "parent_remote_id" field.
func ParentRemoteIDContainsFold(v string) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldContainsFold(FieldParentRemoteID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldContainsFold(FieldStatus, v))
}

// TotalFilesEQ applies the EQ predicate on the "total_files" field.
func TotalFilesEQ(v int) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldEQ(FieldTotalFiles, v))
}

// TotalFilesNEQ applies the NEQ predicate on the "total_files" field.
func TotalFilesNEQ(v int) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldNEQ(FieldTotalFiles, v))
}

// TotalFilesIn applies the In predicate on the "total_files" field.
func TotalFilesIn(vs ...int) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldIn(FieldTotalFiles, vs...))
}

// TotalFilesNotIn applies the NotIn predicate on the "total_files" field.
func TotalFilesNotIn(vs ...int) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldNotIn(FieldTotalFiles, vs...))
}

// TotalFilesGT applies the GT predicate on the "total_files" field.
func TotalFilesGT(v int) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldGT(FieldTotalFiles, v))
}

// TotalFilesGTE applies the GTE predicate on the "total_files" field.
func TotalFilesGTE(v int) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldGTE(FieldTotalFiles, v))
}

// TotalFilesLT applies the LT predicate on the "total_files" field.
func TotalFilesLT(v int) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldLT(FieldTotalFiles, v))
}

// TotalFilesLTE applies the LTE predicate on the "total_files" field.
func TotalFilesLTE(v int) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldLTE(FieldTotalFiles, v))
}

// CompletedFilesEQ applies the EQ predicate on the "completed_files" field.
func CompletedFilesEQ(v int) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldEQ(FieldCompletedFiles, v))
}

// CompletedFilesNEQ applies the NEQ predicate on the "completed_files" field.
func CompletedFilesNEQ(v int) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldNEQ(FieldCompletedFiles, v))
}

// CompletedFilesIn applies the In predicate on the "completed_files" field.
func CompletedFilesIn(vs ...int) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldIn(FieldCompletedFiles, vs...))
}

// CompletedFilesNotIn applies the NotIn predicate on the "completed_files" field.
func CompletedFilesNotIn(vs ...int) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldNotIn(FieldCompletedFiles, vs...))
}

// CompletedFilesGT applies the GT predicate on the "completed_files" field.
func CompletedFilesGT(v int) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldGT(FieldCompletedFiles, v))
}

// CompletedFilesGTE applies the GTE predicate on the "completed_files" field.
func CompletedFilesGTE(v int) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldGTE(FieldCompletedFiles, v))
}

// CompletedFilesLT applies the LT predicate on the "completed_files" field.
func CompletedFilesLT(v int) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldLT(FieldCompletedFiles, v))
}

// CompletedFilesLTE applies the LTE predicate on the "completed_files" field.
func CompletedFilesLTE(v int) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldLTE(FieldCompletedFiles, v))
}

// FailedFilesEQ applies the EQ predicate on the "failed_files" field.
func FailedFilesEQ(v int) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldEQ(FieldFailedFiles, v))
}

// FailedFilesNEQ applies the NEQ predicate on the "failed_files" field.
func FailedFilesNEQ(v int) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldNEQ(FieldFailedFiles, v))
}

// FailedFilesIn applies the In predicate on the "failed_files" field.
func FailedFilesIn(vs ...int) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldIn(FieldFailedFiles, vs...))
}

// FailedFilesNotIn applies the NotIn predicate on the "failed_files" field.
func FailedFilesNotIn(vs ...int) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldNotIn(FieldFailedFiles, vs...))
}

// FailedFilesGT applies the GT predicate on the "failed_files" field.
func FailedFilesGT(v int) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldGT(FieldFailedFiles, v))
}

// FailedFilesGTE applies the GTE predicate on the "failed_files" field.
func FailedFilesGTE(v int) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldGTE(FieldFailedFiles, v))
}

// FailedFilesLT applies the LT predicate on the "failed_files" field.
func FailedFilesLT(v int) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldLT(FieldFailedFiles, v))
}

// FailedFilesLTE applies the LTE predicate on the "failed_files" field.
func FailedFilesLTE(v int) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldLTE(FieldFailedFiles, v))
}

// TotalBytesEQ applies the EQ predicate on the "total_bytes" field.
func TotalBytesEQ(v int64) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldEQ(FieldTotalBytes, v))
}

// TotalBytesNEQ applies the NEQ predicate on the "total_bytes" field.
func TotalBytesNEQ(v int64) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldNEQ(FieldTotalBytes, v))
}

// TotalBytesIn applies the In predicate on the "total_bytes" field.
func TotalBytesIn(vs ...int64) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldIn(FieldTotalBytes, vs...))
}

// TotalBytesNotIn applies the NotIn predicate on the "total_bytes" field.
func TotalBytesNotIn(vs ...int64) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldNotIn(FieldTotalBytes, vs...))
}

// TotalBytesGT applies the GT predicate on the "total_bytes" field.
func TotalBytesGT(v int64) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldGT(FieldTotalBytes, v))
}

// TotalBytesGTE applies the GTE predicate on the "total_bytes" field.
func TotalBytesGTE(v int64) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldGTE(FieldTotalBytes, v))
}

// TotalBytesLT applies the LT predicate on the "total_bytes" field.
func TotalBytesLT(v int64) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldLT(FieldTotalBytes, v))
}

// TotalBytesLTE applies the LTE predicate on the "total_bytes" field.
func TotalBytesLTE(v int64) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldLTE(FieldTotalBytes, v))
}

// TransferredBytesEQ applies the EQ predicate on the "transferred_bytes" field.
func TransferredBytesEQ(v int64) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldEQ(FieldTransferredBytes, v))
}

// TransferredBytesNEQ applies the NEQ predicate on the "transferred_bytes" field.
func TransferredBytesNEQ(v int64) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldNEQ(FieldTransferredBytes, v))
}

// TransferredBytesIn applies the In predicate on the "transferred_bytes" field.
func TransferredBytesIn(vs ...int64) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldIn(FieldTransferredBytes, vs...))
}

// TransferredBytesNotIn applies the NotIn predicate on the "transferred_bytes" field.
func TransferredBytesNotIn(vs ...int64) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldNotIn(FieldTransferredBytes, vs...))
}

// TransferredBytesGT applies the GT predicate on the "transferred_bytes" field.
func TransferredBytesGT(v int64) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldGT(FieldTransferredBytes, v))
}

// TransferredBytesGTE applies the GTE predicate on the "transferred_bytes" field.
func TransferredBytesGTE(v int64) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldGTE(FieldTransferredBytes, v))
}

// TransferredBytesLT applies the LT predicate on the "transferred_bytes" field.
func TransferredBytesLT(v int64) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldLT(FieldTransferredBytes, v))
}

// TransferredBytesLTE applies the LTE predicate on the "transferred_bytes" field.
func TransferredBytesLTE(v int64) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldLTE(FieldTransferredBytes, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldLTE(FieldCreatedAt, v))
}

// CompletedAtEQ applies the EQ predicate on the "completed_at" field.
func CompletedAtEQ(v time.Time) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedAtNEQ applies the NEQ predicate on the "completed_at" field.
func CompletedAtNEQ(v time.Time) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldNEQ(FieldCompletedAt, v))
}

// CompletedAtIn applies the In predicate on the "completed_at" field.
func CompletedAtIn(vs ...time.Time) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldIn(FieldCompletedAt, vs...))
}

// CompletedAtNotIn applies the NotIn predicate on the "completed_at" field.
func CompletedAtNotIn(vs ...time.Time) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldNotIn(FieldCompletedAt, vs...))
}

// CompletedAtGT applies the GT predicate on the "completed_at" field.
func CompletedAtGT(v time.Time) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldGT(FieldCompletedAt, v))
}

// CompletedAtGTE applies the GTE predicate on the "completed_at" field.
func CompletedAtGTE(v time.Time) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldGTE(FieldCompletedAt, v))
}

// CompletedAtLT applies the LT predicate on the "completed_at" field.
func CompletedAtLT(v time.Time) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldLT(FieldCompletedAt, v))
}

// CompletedAtLTE applies the LTE predicate on the "completed_at" field.
func CompletedAtLTE(v time.Time) predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldLTE(FieldCompletedAt, v))
}

// CompletedAtIsNil applies the IsNil predicate on the "completed_at" field.
func CompletedAtIsNil() predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldIsNull(FieldCompletedAt))
}

// CompletedAtNotNil applies the NotNil predicate on the "completed_at" field.
func CompletedAtNotNil() predicate.UploadBatch {
	return predicate.UploadBatch(sql.FieldNotNull(FieldCompletedAt))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.UploadBatch {
	return predicate.UploadBatch(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.UploadBatch {
	return predicate.UploadBatch(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasFiles applies the HasEdge predicate on the "files" edge.
func HasFiles() predicate.UploadBatch {
	return predicate.UploadBatch(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, FilesTable, FilesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFilesWith applies the HasEdge predicate on the "files" edge with a given conditions (other predicates).
func HasFilesWith(preds ...predicate.UploadBatchFile) predicate.UploadBatch {
	return predicate.UploadBatch(func(s *sql.Selector) {
		step := newFilesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UploadBatch) predicate.UploadBatch {
	return predicate.UploadBatch(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UploadBatch) predicate.UploadBatch {
	return predicate.UploadBatch(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UploadBatch) predicate.UploadBatch {
	return predicate.UploadBatch(sql.NotPredicates(p))
}
