// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/drivebase/drivebase/internal/ent/bandwidthlog"
	"github.com/drivebase/drivebase/internal/ent/user"
	"github.com/google/uuid"
)

// BandwidthLog is the model entity for the BandwidthLog schema.
type BandwidthLog struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// ProviderID holds the value of the "provider_id" field.
	ProviderID uuid.UUID `json:"provider_id,omitempty"`
	// Direction holds the value of the "direction" field.
	Direction string `json:"direction,omitempty"`
	// Bytes holds the value of the "bytes" field.
	Bytes int64 `json:"bytes,omitempty"`
	// PeriodStart holds the value of the "period_start" field.
	PeriodStart time.Time `json:"period_start,omitempty"`
	// PeriodEnd holds the value of the "period_end" field.
	PeriodEnd time.Time `json:"period_end,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BandwidthLogQuery when eager-loading is set.
	Edges        BandwidthLogEdges `json:"edges"`
	selectValues sql.SelectValues
}

// BandwidthLogEdges holds the relations/edges for other nodes in the graph.
type BandwidthLogEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BandwidthLogEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BandwidthLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case bandwidthlog.FieldBytes:
			values[i] = new(sql.NullInt64)
		case bandwidthlog.FieldDirection:
			values[i] = new(sql.NullString)
		case bandwidthlog.FieldPeriodStart, bandwidthlog.FieldPeriodEnd, bandwidthlog.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case bandwidthlog.FieldID, bandwidthlog.FieldUserID, bandwidthlog.FieldProviderID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BandwidthLog fields.
func (_m *BandwidthLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case bandwidthlog.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case bandwidthlog.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				_m.UserID = *value
			}
		case bandwidthlog.FieldProviderID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field provider_id", values[i])
			} else if value != nil {
				_m.ProviderID = *value
			}
		case bandwidthlog.FieldDirection:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field direction", values[i])
			} else if value.Valid {
				_m.Direction = value.String
			}
		case bandwidthlog.FieldBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field bytes", values[i])
			} else if value.Valid {
				_m.Bytes = value.Int64
			}
		case bandwidthlog.FieldPeriodStart:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field period_start", values[i])
			} else if value.Valid {
				_m.PeriodStart = value.Time
			}
		case bandwidthlog.FieldPeriodEnd:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field period_end", values[i])
			} else if value.Valid {
				_m.PeriodEnd = value.Time
			}
		case bandwidthlog.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BandwidthLog.
// This includes values selected through modifiers, order, etc.
func (_m *BandwidthLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the BandwidthLog entity.
func (_m *BandwidthLog) QueryUser() *UserQuery {
	return NewBandwidthLogClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this BandwidthLog.
// Note that you need to call BandwidthLog.Unwrap() before calling this method if this BandwidthLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BandwidthLog) Update() *BandwidthLogUpdateOne {
	return NewBandwidthLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BandwidthLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BandwidthLog) Unwrap() *BandwidthLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BandwidthLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BandwidthLog) String() string {
	var builder strings.Builder
	builder.WriteString("BandwidthLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("provider_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProviderID))
	builder.WriteString(", ")
	builder.WriteString("direction=")
	builder.WriteString(_m.Direction)
	builder.WriteString(", ")
	builder.WriteString("bytes=")
	builder.WriteString(fmt.Sprintf("%v", _m.Bytes))
	builder.WriteString(", ")
	builder.WriteString("period_start=")
	builder.WriteString(_m.PeriodStart.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("period_end=")
	builder.WriteString(_m.PeriodEnd.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// BandwidthLogs is a parsable slice of BandwidthLog.
type BandwidthLogs []*BandwidthLog
