// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/drivebase/drivebase/internal/ent/cacheconfig"
	"github.com/drivebase/drivebase/internal/ent/provider"
	"github.com/google/uuid"
)

// CacheConfigCreate is the builder for creating a CacheConfig entity.
type CacheConfigCreate struct {
	config
	mutation *CacheConfigMutation
	hooks    []Hook
}

// SetProviderID sets the "provider_id" field.
func (_c *CacheConfigCreate) SetProviderID(v uuid.UUID) *CacheConfigCreate {
	_c.mutation.SetProviderID(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *CacheConfigCreate) SetEnabled(v bool) *CacheConfigCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *CacheConfigCreate) SetNillableEnabled(v *bool) *CacheConfigCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetMaxSizeBytes sets the "max_size_bytes" field.
func (_c *CacheConfigCreate) SetMaxSizeBytes(v int64) *CacheConfigCreate {
	_c.mutation.SetMaxSizeBytes(v)
	return _c
}

// SetNillableMaxSizeBytes sets the "max_size_bytes" field if the given value is not nil.
func (_c *CacheConfigCreate) SetNillableMaxSizeBytes(v *int64) *CacheConfigCreate {
	if v != nil {
		_c.SetMaxSizeBytes(*v)
	}
	return _c
}

// SetTTLSeconds sets the "ttl_seconds" field.
func (_c *CacheConfigCreate) SetTTLSeconds(v int) *CacheConfigCreate {
	_c.mutation.SetTTLSeconds(v)
	return _c
}

// SetNillableTTLSeconds sets the "ttl_seconds" field if the given value is not nil.
func (_c *CacheConfigCreate) SetNillableTTLSeconds(v *int) *CacheConfigCreate {
	if v != nil {
		_c.SetTTLSeconds(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CacheConfigCreate) SetCreatedAt(v time.Time) *CacheConfigCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CacheConfigCreate) SetNillableCreatedAt(v *time.Time) *CacheConfigCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CacheConfigCreate) SetUpdatedAt(v time.Time) *CacheConfigCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CacheConfigCreate) SetNillableUpdatedAt(v *time.Time) *CacheConfigCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *CacheConfigCreate) SetID(v uuid.UUID) *CacheConfigCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *CacheConfigCreate) SetNillableID(v *uuid.UUID) *CacheConfigCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetProvider sets the "provider" edge to the Provider entity.
func (_c *CacheConfigCreate) SetProvider(v *Provider) *CacheConfigCreate {
	return _c.SetProviderID(v.ID)
}

// Mutation returns the CacheConfigMutation object of the builder.
func (_c *CacheConfigCreate) Mutation() *CacheConfigMutation {
	return _c.mutation
}

// Save creates the CacheConfig in the database.
func (_c *CacheConfigCreate) Save(ctx context.Context) (*CacheConfig, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CacheConfigCreate) SaveX(ctx context.Context) *CacheConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CacheConfigCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CacheConfigCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CacheConfigCreate) defaults() {
	if _, ok := _c.mutation.Enabled(); !ok {
		v := cacheconfig.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.MaxSizeBytes(); !ok {
		v := cacheconfig.DefaultMaxSizeBytes
		_c.mutation.SetMaxSizeBytes(v)
	}
	if _, ok := _c.mutation.TTLSeconds(); !ok {
		v := cacheconfig.DefaultTTLSeconds
		_c.mutation.SetTTLSeconds(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := cacheconfig.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := cacheconfig.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := cacheconfig.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CacheConfigCreate) check() error {
	if _, ok := _c.mutation.ProviderID(); !ok {
		return &ValidationError{Name: "provider_id", err: errors.New(`ent: missing required field "CacheConfig.provider_id"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "CacheConfig.enabled"`)}
	}
	if _, ok := _c.mutation.MaxSizeBytes(); !ok {
		return &ValidationError{Name: "max_size_bytes", err: errors.New(`ent: missing required field "CacheConfig.max_size_bytes"`)}
	}
	if _, ok := _c.mutation.TTLSeconds(); !ok {
		return &ValidationError{Name: "ttl_seconds", err: errors.New(`ent: missing required field "CacheConfig.ttl_seconds"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CacheConfig.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CacheConfig.updated_at"`)}
	}
	if len(_c.mutation.ProviderIDs()) == 0 {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required edge "CacheConfig.provider"`)}
	}
	return nil
}

func (_c *CacheConfigCreate) sqlSave(ctx context.Context) (*CacheConfig, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CacheConfigCreate) createSpec() (*CacheConfig, *sqlgraph.CreateSpec) {
	var (
		_node = &CacheConfig{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(cacheconfig.Table, sqlgraph.NewFieldSpec(cacheconfig.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(cacheconfig.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.MaxSizeBytes(); ok {
		_spec.SetField(cacheconfig.FieldMaxSizeBytes, field.TypeInt64, value)
		_node.MaxSizeBytes = value
	}
	if value, ok := _c.mutation.TTLSeconds(); ok {
		_spec.SetField(cacheconfig.FieldTTLSeconds, field.TypeInt, value)
		_node.TTLSeconds = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(cacheconfig.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(cacheconfig.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ProviderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   cacheconfig.ProviderTable,
			Columns: []string{cacheconfig.ProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(provider.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProviderID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CacheConfigCreateBulk is the builder for creating many CacheConfig entities in bulk.
type CacheConfigCreateBulk struct {
	config
	err      error
	builders []*CacheConfigCreate
}

// Save creates the CacheConfig entities in the database.
func (_c *CacheConfigCreateBulk) Save(ctx context.Context) ([]*CacheConfig, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CacheConfig, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CacheConfigMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CacheConfigCreateBulk) SaveX(ctx context.Context) []*CacheConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CacheConfigCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CacheConfigCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
