// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/drivebase/drivebase/internal/ent/filenode"
	"github.com/drivebase/drivebase/internal/ent/provider"
	"github.com/google/uuid"
)

// FileNodeCreate is the builder for creating a FileNode entity.
type FileNodeCreate struct {
	config
	mutation *FileNodeMutation
	hooks    []Hook
}

// SetProviderID sets the "provider_id" field.
func (_c *FileNodeCreate) SetProviderID(v uuid.UUID) *FileNodeCreate {
	_c.mutation.SetProviderID(v)
	return _c
}

// SetParentID sets the "parent_id" field.
func (_c *FileNodeCreate) SetParentID(v uuid.UUID) *FileNodeCreate {
	_c.mutation.SetParentID(v)
	return _c
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_c *FileNodeCreate) SetNillableParentID(v *uuid.UUID) *FileNodeCreate {
	if v != nil {
		_c.SetParentID(*v)
	}
	return _c
}

// SetRemoteID sets the "remote_id" field.
func (_c *FileNodeCreate) SetRemoteID(v string) *FileNodeCreate {
	_c.mutation.SetRemoteID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *FileNodeCreate) SetName(v string) *FileNodeCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetIsDir sets the "is_dir" field.
func (_c *FileNodeCreate) SetIsDir(v bool) *FileNodeCreate {
	_c.mutation.SetIsDir(v)
	return _c
}

// SetNillableIsDir sets the "is_dir" field if the given value is not nil.
func (_c *FileNodeCreate) SetNillableIsDir(v *bool) *FileNodeCreate {
	if v != nil {
		_c.SetIsDir(*v)
	}
	return _c
}

// SetSize sets the "size" field.
func (_c *FileNodeCreate) SetSize(v int64) *FileNodeCreate {
	_c.mutation.SetSize(v)
	return _c
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_c *FileNodeCreate) SetNillableSize(v *int64) *FileNodeCreate {
	if v != nil {
		_c.SetSize(*v)
	}
	return _c
}

// SetMimeType sets the "mime_type" field.
func (_c *FileNodeCreate) SetMimeType(v string) *FileNodeCreate {
	_c.mutation.SetMimeType(v)
	return _c
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_c *FileNodeCreate) SetNillableMimeType(v *string) *FileNodeCreate {
	if v != nil {
		_c.SetMimeType(*v)
	}
	return _c
}

// SetChecksum sets the "checksum" field.
func (_c *FileNodeCreate) SetChecksum(v string) *FileNodeCreate {
	_c.mutation.SetChecksum(v)
	return _c
}

// SetNillableChecksum sets the "checksum" field if the given value is not nil.
func (_c *FileNodeCreate) SetNillableChecksum(v *string) *FileNodeCreate {
	if v != nil {
		_c.SetChecksum(*v)
	}
	return _c
}

// SetRemoteModifiedAt sets the "remote_modified_at" field.
func (_c *FileNodeCreate) SetRemoteModifiedAt(v time.Time) *FileNodeCreate {
	_c.mutation.SetRemoteModifiedAt(v)
	return _c
}

// SetNillableRemoteModifiedAt sets the "remote_modified_at" field if the given value is not nil.
func (_c *FileNodeCreate) SetNillableRemoteModifiedAt(v *time.Time) *FileNodeCreate {
	if v != nil {
		_c.SetRemoteModifiedAt(*v)
	}
	return _c
}

// SetSyncedAt sets the "synced_at" field.
func (_c *FileNodeCreate) SetSyncedAt(v time.Time) *FileNodeCreate {
	_c.mutation.SetSyncedAt(v)
	return _c
}

// SetNillableSyncedAt sets the "synced_at" field if the given value is not nil.
func (_c *FileNodeCreate) SetNillableSyncedAt(v *time.Time) *FileNodeCreate {
	if v != nil {
		_c.SetSyncedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *FileNodeCreate) SetCreatedAt(v time.Time) *FileNodeCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *FileNodeCreate) SetNillableCreatedAt(v *time.Time) *FileNodeCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *FileNodeCreate) SetID(v uuid.UUID) *FileNodeCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *FileNodeCreate) SetNillableID(v *uuid.UUID) *FileNodeCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetProvider sets the "provider" edge to the Provider entity.
func (_c *FileNodeCreate) SetProvider(v *Provider) *FileNodeCreate {
	return _c.SetProviderID(v.ID)
}

// SetParent sets the "parent" edge to the FileNode entity.
func (_c *FileNodeCreate) SetParent(v *FileNode) *FileNodeCreate {
	return _c.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the FileNode entity by IDs.
func (_c *FileNodeCreate) AddChildIDs(ids ...uuid.UUID) *FileNodeCreate {
	_c.mutation.AddChildIDs(ids...)
	return _c
}

// AddChildren adds the "children" edges to the FileNode entity.
func (_c *FileNodeCreate) AddChildren(v ...*FileNode) *FileNodeCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddChildIDs(ids...)
}

// Mutation returns the FileNodeMutation object of the builder.
func (_c *FileNodeCreate) Mutation() *FileNodeMutation {
	return _c.mutation
}

// Save creates the FileNode in the database.
func (_c *FileNodeCreate) Save(ctx context.Context) (*FileNode, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *FileNodeCreate) SaveX(ctx context.Context) *FileNode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FileNodeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FileNodeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *FileNodeCreate) defaults() {
	if _, ok := _c.mutation.IsDir(); !ok {
		v := filenode.DefaultIsDir
		_c.mutation.SetIsDir(v)
	}
	if _, ok := _c.mutation.Size(); !ok {
		v := filenode.DefaultSize
		_c.mutation.SetSize(v)
	}
	if _, ok := _c.mutation.SyncedAt(); !ok {
		v := filenode.DefaultSyncedAt()
		_c.mutation.SetSyncedAt(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := filenode.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := filenode.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *FileNodeCreate) check() error {
	if _, ok := _c.mutation.ProviderID(); !ok {
		return &ValidationError{Name: "provider_id", err: errors.New(`ent: missing required field "FileNode.provider_id"`)}
	}
	if _, ok := _c.mutation.RemoteID(); !ok {
		return &ValidationError{Name: "remote_id", err: errors.New(`ent: missing required field "FileNode.remote_id"`)}
	}
	if v, ok := _c.mutation.RemoteID(); ok {
		if err := filenode.RemoteIDValidator(v); err != nil {
			return &ValidationError{Name: "remote_id", err: fmt.Errorf(`ent: validator failed for field "FileNode.remote_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "FileNode.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := filenode.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "FileNode.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsDir(); !ok {
		return &ValidationError{Name: "is_dir", err: errors.New(`ent: missing required field "FileNode.is_dir"`)}
	}
	if _, ok := _c.mutation.Size(); !ok {
		return &ValidationError{Name: "size", err: errors.New(`ent: missing required field "FileNode.size"`)}
	}
	if _, ok := _c.mutation.SyncedAt(); !ok {
		return &ValidationError{Name: "synced_at", err: errors.New(`ent: missing required field "FileNode.synced_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "FileNode.created_at"`)}
	}
	if len(_c.mutation.ProviderIDs()) == 0 {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required edge "FileNode.provider"`)}
	}
	return nil
}

func (_c *FileNodeCreate) sqlSave(ctx context.Context) (*FileNode, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *FileNodeCreate) createSpec() (*FileNode, *sqlgraph.CreateSpec) {
	var (
		_node = &FileNode{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(filenode.Table, sqlgraph.NewFieldSpec(filenode.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.RemoteID(); ok {
		_spec.SetField(filenode.FieldRemoteID, field.TypeString, value)
		_node.RemoteID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(filenode.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.IsDir(); ok {
		_spec.SetField(filenode.FieldIsDir, field.TypeBool, value)
		_node.IsDir = value
	}
	if value, ok := _c.mutation.Size(); ok {
		_spec.SetField(filenode.FieldSize, field.TypeInt64, value)
		_node.Size = value
	}
	if value, ok := _c.mutation.MimeType(); ok {
		_spec.SetField(filenode.FieldMimeType, field.TypeString, value)
		_node.MimeType = value
	}
	if value, ok := _c.mutation.Checksum(); ok {
		_spec.SetField(filenode.FieldChecksum, field.TypeString, value)
		_node.Checksum = value
	}
	if value, ok := _c.mutation.RemoteModifiedAt(); ok {
		_spec.SetField(filenode.FieldRemoteModifiedAt, field.TypeTime, value)
		_node.RemoteModifiedAt = &value
	}
	if value, ok := _c.mutation.SyncedAt(); ok {
		_spec.SetField(filenode.FieldSyncedAt, field.TypeTime, value)
		_node.SyncedAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(filenode.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.ProviderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   filenode.ProviderTable,
			Columns: []string{filenode.ProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(provider.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProviderID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   filenode.ParentTable,
			Columns: []string{filenode.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(filenode.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ParentID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   filenode.ChildrenTable,
			Columns: []string{filenode.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(filenode.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// FileNodeCreateBulk is the builder for creating many FileNode entities in bulk.
type FileNodeCreateBulk struct {
	config
	err      error
	builders []*FileNodeCreate
}

// Save creates the FileNode entities in the database.
func (_c *FileNodeCreateBulk) Save(ctx context.Context) ([]*FileNode, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*FileNode, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FileNodeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *FileNodeCreateBulk) SaveX(ctx context.Context) []*FileNode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FileNodeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FileNodeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
