// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/drivebase/drivebase/internal/ent/oauthapp"
	"github.com/drivebase/drivebase/internal/ent/workspace"
	"github.com/google/uuid"
)

// OAuthAppCreate is the builder for creating a OAuthApp entity.
type OAuthAppCreate struct {
	config
	mutation *OAuthAppMutation
	hooks    []Hook
}

// SetWorkspaceID sets the "workspace_id" field.
func (_c *OAuthAppCreate) SetWorkspaceID(v uuid.UUID) *OAuthAppCreate {
	_c.mutation.SetWorkspaceID(v)
	return _c
}

// SetProviderType sets the "provider_type" field.
func (_c *OAuthAppCreate) SetProviderType(v string) *OAuthAppCreate {
	_c.mutation.SetProviderType(v)
	return _c
}

// SetClientID sets the "client_id" field.
func (_c *OAuthAppCreate) SetClientID(v string) *OAuthAppCreate {
	_c.mutation.SetClientID(v)
	return _c
}

// SetEncryptedClientSecret sets the "encrypted_client_secret" field.
func (_c *OAuthAppCreate) SetEncryptedClientSecret(v []byte) *OAuthAppCreate {
	_c.mutation.SetEncryptedClientSecret(v)
	return _c
}

// SetAlias sets the "alias" field.
func (_c *OAuthAppCreate) SetAlias(v string) *OAuthAppCreate {
	_c.mutation.SetAlias(v)
	return _c
}

// SetNillableAlias sets the "alias" field if the given value is not nil.
func (_c *OAuthAppCreate) SetNillableAlias(v *string) *OAuthAppCreate {
	if v != nil {
		_c.SetAlias(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *OAuthAppCreate) SetCreatedAt(v time.Time) *OAuthAppCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OAuthAppCreate) SetNillableCreatedAt(v *time.Time) *OAuthAppCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OAuthAppCreate) SetUpdatedAt(v time.Time) *OAuthAppCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OAuthAppCreate) SetNillableUpdatedAt(v *time.Time) *OAuthAppCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *OAuthAppCreate) SetID(v uuid.UUID) *OAuthAppCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *OAuthAppCreate) SetNillableID(v *uuid.UUID) *OAuthAppCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetWorkspace sets the "workspace" edge to the Workspace entity.
func (_c *OAuthAppCreate) SetWorkspace(v *Workspace) *OAuthAppCreate {
	return _c.SetWorkspaceID(v.ID)
}

// Mutation returns the OAuthAppMutation object of the builder.
func (_c *OAuthAppCreate) Mutation() *OAuthAppMutation {
	return _c.mutation
}

// Save creates the OAuthApp in the database.
func (_c *OAuthAppCreate) Save(ctx context.Context) (*OAuthApp, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OAuthAppCreate) SaveX(ctx context.Context) *OAuthApp {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthAppCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthAppCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OAuthAppCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := oauthapp.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := oauthapp.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := oauthapp.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OAuthAppCreate) check() error {
	if _, ok := _c.mutation.WorkspaceID(); !ok {
		return &ValidationError{Name: "workspace_id", err: errors.New(`ent: missing required field "OAuthApp.workspace_id"`)}
	}
	if _, ok := _c.mutation.ProviderType(); !ok {
		return &ValidationError{Name: "provider_type", err: errors.New(`ent: missing required field "OAuthApp.provider_type"`)}
	}
	if v, ok := _c.mutation.ProviderType(); ok {
		if err := oauthapp.ProviderTypeValidator(v); err != nil {
			return &ValidationError{Name: "provider_type", err: fmt.Errorf(`ent: validator failed for field "OAuthApp.provider_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ClientID(); !ok {
		return &ValidationError{Name: "client_id", err: errors.New(`ent: missing required field "OAuthApp.client_id"`)}
	}
	if v, ok := _c.mutation.ClientID(); ok {
		if err := oauthapp.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "OAuthApp.client_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EncryptedClientSecret(); !ok {
		return &ValidationError{Name: "encrypted_client_secret", err: errors.New(`ent: missing required field "OAuthApp.encrypted_client_secret"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OAuthApp.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OAuthApp.updated_at"`)}
	}
	if len(_c.mutation.WorkspaceIDs()) == 0 {
		return &ValidationError{Name: "workspace", err: errors.New(`ent: missing required edge "OAuthApp.workspace"`)}
	}
	return nil
}

func (_c *OAuthAppCreate) sqlSave(ctx context.Context) (*OAuthApp, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OAuthAppCreate) createSpec() (*OAuthApp, *sqlgraph.CreateSpec) {
	var (
		_node = &OAuthApp{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(oauthapp.Table, sqlgraph.NewFieldSpec(oauthapp.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.ProviderType(); ok {
		_spec.SetField(oauthapp.FieldProviderType, field.TypeString, value)
		_node.ProviderType = value
	}
	if value, ok := _c.mutation.ClientID(); ok {
		_spec.SetField(oauthapp.FieldClientID, field.TypeString, value)
		_node.ClientID = value
	}
	if value, ok := _c.mutation.EncryptedClientSecret(); ok {
		_spec.SetField(oauthapp.FieldEncryptedClientSecret, field.TypeBytes, value)
		_node.EncryptedClientSecret = value
	}
	if value, ok := _c.mutation.Alias(); ok {
		_spec.SetField(oauthapp.FieldAlias, field.TypeString, value)
		_node.Alias = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(oauthapp.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthapp.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.WorkspaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthapp.WorkspaceTable,
			Columns: []string{oauthapp.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.WorkspaceID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OAuthAppCreateBulk is the builder for creating many OAuthApp entities in bulk.
type OAuthAppCreateBulk struct {
	config
	err      error
	builders []*OAuthAppCreate
}

// Save creates the OAuthApp entities in the database.
func (_c *OAuthAppCreateBulk) Save(ctx context.Context) ([]*OAuthApp, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OAuthApp, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OAuthAppMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OAuthAppCreateBulk) SaveX(ctx context.Context) []*OAuthApp {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthAppCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthAppCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
