// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/drivebase/drivebase/internal/ent/oauthstate"
	"github.com/google/uuid"
)

// OAuthState is the model entity for the OAuthState schema.
type OAuthState struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// WorkspaceID holds the value of the "workspace_id" field.
	WorkspaceID uuid.UUID `json:"workspace_id,omitempty"`
	// OauthAppID holds the value of the "oauth_app_id" field.
	OauthAppID uuid.UUID `json:"oauth_app_id,omitempty"`
	// ProviderType holds the value of the "provider_type" field.
	ProviderType string `json:"provider_type,omitempty"`
	// ProviderName holds the value of the "provider_name" field.
	ProviderName string `json:"provider_name,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OAuthState) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case oauthstate.FieldProviderType, oauthstate.FieldProviderName:
			values[i] = new(sql.NullString)
		case oauthstate.FieldExpiresAt, oauthstate.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case oauthstate.FieldID, oauthstate.FieldWorkspaceID, oauthstate.FieldOauthAppID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OAuthState fields.
func (_m *OAuthState) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case oauthstate.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case oauthstate.FieldWorkspaceID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field workspace_id", values[i])
			} else if value != nil {
				_m.WorkspaceID = *value
			}
		case oauthstate.FieldOauthAppID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field oauth_app_id", values[i])
			} else if value != nil {
				_m.OauthAppID = *value
			}
		case oauthstate.FieldProviderType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_type", values[i])
			} else if value.Valid {
				_m.ProviderType = value.String
			}
		case oauthstate.FieldProviderName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_name", values[i])
			} else if value.Valid {
				_m.ProviderName = value.String
			}
		case oauthstate.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case oauthstate.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OAuthState.
// This includes values selected through modifiers, order, etc.
func (_m *OAuthState) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this OAuthState.
// Note that you need to call OAuthState.Unwrap() before calling this method if this OAuthState
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OAuthState) Update() *OAuthStateUpdateOne {
	return NewOAuthStateClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OAuthState entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OAuthState) Unwrap() *OAuthState {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OAuthState is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OAuthState) String() string {
	var builder strings.Builder
	builder.WriteString("OAuthState(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("workspace_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.WorkspaceID))
	builder.WriteString(", ")
	builder.WriteString("oauth_app_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OauthAppID))
	builder.WriteString(", ")
	builder.WriteString("provider_type=")
	builder.WriteString(_m.ProviderType)
	builder.WriteString(", ")
	builder.WriteString("provider_name=")
	builder.WriteString(_m.ProviderName)
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// OAuthStates is a parsable slice of OAuthState.
type OAuthStates []*OAuthState
