// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/drivebase/drivebase/internal/ent/permission"
	"github.com/drivebase/drivebase/internal/ent/predicate"
	"github.com/drivebase/drivebase/internal/ent/role"
	"github.com/google/uuid"
)

// PermissionUpdate is the builder for updating Permission entities.
type PermissionUpdate struct {
	config
	hooks    []Hook
	mutation *PermissionMutation
}

// Where appends a list predicates to the PermissionUpdate builder.
func (_u *PermissionUpdate) Where(ps ...predicate.Permission) *PermissionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRoleID sets the "role_id" field.
func (_u *PermissionUpdate) SetRoleID(v uuid.UUID) *PermissionUpdate {
	_u.mutation.SetRoleID(v)
	return _u
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (_u *PermissionUpdate) SetNillableRoleID(v *uuid.UUID) *PermissionUpdate {
	if v != nil {
		_u.SetRoleID(*v)
	}
	return _u
}

// SetResourceType sets the "resource_type" field.
func (_u *PermissionUpdate) SetResourceType(v string) *PermissionUpdate {
	_u.mutation.SetResourceType(v)
	return _u
}

// SetNillableResourceType sets the "resource_type" field if the given value is not nil.
func (_u *PermissionUpdate) SetNillableResourceType(v *string) *PermissionUpdate {
	if v != nil {
		_u.SetResourceType(*v)
	}
	return _u
}

// SetResourceID sets the "resource_id" field.
func (_u *PermissionUpdate) SetResourceID(v uuid.UUID) *PermissionUpdate {
	_u.mutation.SetResourceID(v)
	return _u
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (_u *PermissionUpdate) SetNillableResourceID(v *uuid.UUID) *PermissionUpdate {
	if v != nil {
		_u.SetResourceID(*v)
	}
	return _u
}

// ClearResourceID clears the value of the "resource_id" field.
func (_u *PermissionUpdate) ClearResourceID() *PermissionUpdate {
	_u.mutation.ClearResourceID()
	return _u
}

// SetActions sets the "actions" field.
func (_u *PermissionUpdate) SetActions(v []string) *PermissionUpdate {
	_u.mutation.SetActions(v)
	return _u
}

// AppendActions appends value to the "actions" field.
func (_u *PermissionUpdate) AppendActions(v []string) *PermissionUpdate {
	_u.mutation.AppendActions(v)
	return _u
}

// SetRole sets the "role" edge to the Role entity.
func (_u *PermissionUpdate) SetRole(v *Role) *PermissionUpdate {
	return _u.SetRoleID(v.ID)
}

// Mutation returns the PermissionMutation object of the builder.
func (_u *PermissionUpdate) Mutation() *PermissionMutation {
	return _u.mutation
}

// ClearRole clears the "role" edge to the Role entity.
func (_u *PermissionUpdate) ClearRole() *PermissionUpdate {
	_u.mutation.ClearRole()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PermissionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PermissionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PermissionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PermissionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PermissionUpdate) check() error {
	if v, ok := _u.mutation.ResourceType(); ok {
		if err := permission.ResourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "resource_type", err: fmt.Errorf(`ent: validator failed for field "Permission.resource_type": %w`, err)}
		}
	}
	if _u.mutation.RoleCleared() && len(_u.mutation.RoleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Permission.role"`)
	}
	return nil
}

func (_u *PermissionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(permission.Table, permission.Columns, sqlgraph.NewFieldSpec(permission.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ResourceType(); ok {
		_spec.SetField(permission.FieldResourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceID(); ok {
		_spec.SetField(permission.FieldResourceID, field.TypeUUID, value)
	}
	if _u.mutation.ResourceIDCleared() {
		_spec.ClearField(permission.FieldResourceID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Actions(); ok {
		_spec.SetField(permission.FieldActions, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedActions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, permission.FieldActions, value)
		})
	}
	if _u.mutation.RoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   permission.RoleTable,
			Columns: []string{permission.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   permission.RoleTable,
			Columns: []string{permission.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{permission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PermissionUpdateOne is the builder for updating a single Permission entity.
type PermissionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PermissionMutation
}

// SetRoleID sets the "role_id" field.
func (_u *PermissionUpdateOne) SetRoleID(v uuid.UUID) *PermissionUpdateOne {
	_u.mutation.SetRoleID(v)
	return _u
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (_u *PermissionUpdateOne) SetNillableRoleID(v *uuid.UUID) *PermissionUpdateOne {
	if v != nil {
		_u.SetRoleID(*v)
	}
	return _u
}

// SetResourceType sets the "resource_type" field.
func (_u *PermissionUpdateOne) SetResourceType(v string) *PermissionUpdateOne {
	_u.mutation.SetResourceType(v)
	return _u
}

// SetNillableResourceType sets the "resource_type" field if the given value is not nil.
func (_u *PermissionUpdateOne) SetNillableResourceType(v *string) *PermissionUpdateOne {
	if v != nil {
		_u.SetResourceType(*v)
	}
	return _u
}

// SetResourceID sets the "resource_id" field.
func (_u *PermissionUpdateOne) SetResourceID(v uuid.UUID) *PermissionUpdateOne {
	_u.mutation.SetResourceID(v)
	return _u
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (_u *PermissionUpdateOne) SetNillableResourceID(v *uuid.UUID) *PermissionUpdateOne {
	if v != nil {
		_u.SetResourceID(*v)
	}
	return _u
}

// ClearResourceID clears the value of the "resource_id" field.
func (_u *PermissionUpdateOne) ClearResourceID() *PermissionUpdateOne {
	_u.mutation.ClearResourceID()
	return _u
}

// SetActions sets the "actions" field.
func (_u *PermissionUpdateOne) SetActions(v []string) *PermissionUpdateOne {
	_u.mutation.SetActions(v)
	return _u
}

// AppendActions appends value to the "actions" field.
func (_u *PermissionUpdateOne) AppendActions(v []string) *PermissionUpdateOne {
	_u.mutation.AppendActions(v)
	return _u
}

// SetRole sets the "role" edge to the Role entity.
func (_u *PermissionUpdateOne) SetRole(v *Role) *PermissionUpdateOne {
	return _u.SetRoleID(v.ID)
}

// Mutation returns the PermissionMutation object of the builder.
func (_u *PermissionUpdateOne) Mutation() *PermissionMutation {
	return _u.mutation
}

// ClearRole clears the "role" edge to the Role entity.
func (_u *PermissionUpdateOne) ClearRole() *PermissionUpdateOne {
	_u.mutation.ClearRole()
	return _u
}

// Where appends a list predicates to the PermissionUpdate builder.
func (_u *PermissionUpdateOne) Where(ps ...predicate.Permission) *PermissionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PermissionUpdateOne) Select(field string, fields ...string) *PermissionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Permission entity.
func (_u *PermissionUpdateOne) Save(ctx context.Context) (*Permission, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PermissionUpdateOne) SaveX(ctx context.Context) *Permission {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PermissionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PermissionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PermissionUpdateOne) check() error {
	if v, ok := _u.mutation.ResourceType(); ok {
		if err := permission.ResourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "resource_type", err: fmt.Errorf(`ent: validator failed for field "Permission.resource_type": %w`, err)}
		}
	}
	if _u.mutation.RoleCleared() && len(_u.mutation.RoleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Permission.role"`)
	}
	return nil
}

func (_u *PermissionUpdateOne) sqlSave(ctx context.Context) (_node *Permission, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(permission.Table, permission.Columns, sqlgraph.NewFieldSpec(permission.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Permission.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, permission.FieldID)
		for _, f := range fields {
			if !permission.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != permission.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ResourceType(); ok {
		_spec.SetField(permission.FieldResourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceID(); ok {
		_spec.SetField(permission.FieldResourceID, field.TypeUUID, value)
	}
	if _u.mutation.ResourceIDCleared() {
		_spec.ClearField(permission.FieldResourceID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Actions(); ok {
		_spec.SetField(permission.FieldActions, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedActions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, permission.FieldActions, value)
		})
	}
	if _u.mutation.RoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   permission.RoleTable,
			Columns: []string{permission.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   permission.RoleTable,
			Columns: []string{permission.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Permission{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{permission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
