// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/drivebase/drivebase/internal/ent/provider"
	"github.com/drivebase/drivebase/internal/ent/providercredential"
	"github.com/google/uuid"
)

// ProviderCredential is the model entity for the ProviderCredential schema.
type ProviderCredential struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// ProviderID holds the value of the "provider_id" field.
	ProviderID uuid.UUID `json:"provider_id,omitempty"`
	// EncryptedData holds the value of the "encrypted_data" field.
	EncryptedData []byte `json:"-"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProviderCredentialQuery when eager-loading is set.
	Edges        ProviderCredentialEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ProviderCredentialEdges holds the relations/edges for other nodes in the graph.
type ProviderCredentialEdges struct {
	// Provider holds the value of the provider edge.
	Provider *Provider `json:"provider,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ProviderOrErr returns the Provider value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProviderCredentialEdges) ProviderOrErr() (*Provider, error) {
	if e.Provider != nil {
		return e.Provider, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: provider.Label}
	}
	return nil, &NotLoadedError{edge: "provider"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProviderCredential) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case providercredential.FieldEncryptedData:
			values[i] = new([]byte)
		case providercredential.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case providercredential.FieldID, providercredential.FieldProviderID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProviderCredential fields.
func (_m *ProviderCredential) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case providercredential.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case providercredential.FieldProviderID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field provider_id", values[i])
			} else if value != nil {
				_m.ProviderID = *value
			}
		case providercredential.FieldEncryptedData:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field encrypted_data", values[i])
			} else if value != nil {
				_m.EncryptedData = *value
			}
		case providercredential.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProviderCredential.
// This includes values selected through modifiers, order, etc.
func (_m *ProviderCredential) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProvider queries the "provider" edge of the ProviderCredential entity.
func (_m *ProviderCredential) QueryProvider() *ProviderQuery {
	return NewProviderCredentialClient(_m.config).QueryProvider(_m)
}

// Update returns a builder for updating this ProviderCredential.
// Note that you need to call ProviderCredential.Unwrap() before calling this method if this ProviderCredential
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ProviderCredential) Update() *ProviderCredentialUpdateOne {
	return NewProviderCredentialClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ProviderCredential entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ProviderCredential) Unwrap() *ProviderCredential {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProviderCredential is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ProviderCredential) String() string {
	var builder strings.Builder
	builder.WriteString("ProviderCredential(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("provider_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProviderID))
	builder.WriteString(", ")
	builder.WriteString("encrypted_data=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ProviderCredentials is a parsable slice of ProviderCredential.
type ProviderCredentials []*ProviderCredential
