// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/drivebase/drivebase/internal/ent/predicate"
	"github.com/drivebase/drivebase/internal/ent/schema"
	"github.com/drivebase/drivebase/internal/ent/sharedlink"
	"github.com/drivebase/drivebase/internal/ent/workspace"
	"github.com/google/uuid"
)

// SharedLinkUpdate is the builder for updating SharedLink entities.
type SharedLinkUpdate struct {
	config
	hooks    []Hook
	mutation *SharedLinkMutation
}

// Where appends a list predicates to the SharedLinkUpdate builder.
func (_u *SharedLinkUpdate) Where(ps ...predicate.SharedLink) *SharedLinkUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetWorkspaceID sets the "workspace_id" field.
func (_u *SharedLinkUpdate) SetWorkspaceID(v uuid.UUID) *SharedLinkUpdate {
	_u.mutation.SetWorkspaceID(v)
	return _u
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (_u *SharedLinkUpdate) SetNillableWorkspaceID(v *uuid.UUID) *SharedLinkUpdate {
	if v != nil {
		_u.SetWorkspaceID(*v)
	}
	return _u
}

// SetFileNodeID sets the "file_node_id" field.
func (_u *SharedLinkUpdate) SetFileNodeID(v uuid.UUID) *SharedLinkUpdate {
	_u.mutation.SetFileNodeID(v)
	return _u
}

// SetNillableFileNodeID sets the "file_node_id" field if the given value is not nil.
func (_u *SharedLinkUpdate) SetNillableFileNodeID(v *uuid.UUID) *SharedLinkUpdate {
	if v != nil {
		_u.SetFileNodeID(*v)
	}
	return _u
}

// SetPermissions sets the "permissions" field.
func (_u *SharedLinkUpdate) SetPermissions(v schema.SharedLinkPermissions) *SharedLinkUpdate {
	_u.mutation.SetPermissions(v)
	return _u
}

// SetNillablePermissions sets the "permissions" field if the given value is not nil.
func (_u *SharedLinkUpdate) SetNillablePermissions(v *schema.SharedLinkPermissions) *SharedLinkUpdate {
	if v != nil {
		_u.SetPermissions(*v)
	}
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *SharedLinkUpdate) SetPasswordHash(v string) *SharedLinkUpdate {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *SharedLinkUpdate) SetNillablePasswordHash(v *string) *SharedLinkUpdate {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// ClearPasswordHash clears the value of the "password_hash" field.
func (_u *SharedLinkUpdate) ClearPasswordHash() *SharedLinkUpdate {
	_u.mutation.ClearPasswordHash()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *SharedLinkUpdate) SetExpiresAt(v time.Time) *SharedLinkUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *SharedLinkUpdate) SetNillableExpiresAt(v *time.Time) *SharedLinkUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *SharedLinkUpdate) ClearExpiresAt() *SharedLinkUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetMaxUploads sets the "max_uploads" field.
func (_u *SharedLinkUpdate) SetMaxUploads(v int) *SharedLinkUpdate {
	_u.mutation.ResetMaxUploads()
	_u.mutation.SetMaxUploads(v)
	return _u
}

// SetNillableMaxUploads sets the "max_uploads" field if the given value is not nil.
func (_u *SharedLinkUpdate) SetNillableMaxUploads(v *int) *SharedLinkUpdate {
	if v != nil {
		_u.SetMaxUploads(*v)
	}
	return _u
}

// AddMaxUploads adds value to the "max_uploads" field.
func (_u *SharedLinkUpdate) AddMaxUploads(v int) *SharedLinkUpdate {
	_u.mutation.AddMaxUploads(v)
	return _u
}

// ClearMaxUploads clears the value of the "max_uploads" field.
func (_u *SharedLinkUpdate) ClearMaxUploads() *SharedLinkUpdate {
	_u.mutation.ClearMaxUploads()
	return _u
}

// SetUploadCount sets the "upload_count" field.
func (_u *SharedLinkUpdate) SetUploadCount(v int) *SharedLinkUpdate {
	_u.mutation.ResetUploadCount()
	_u.mutation.SetUploadCount(v)
	return _u
}

// SetNillableUploadCount sets the "upload_count" field if the given value is not nil.
func (_u *SharedLinkUpdate) SetNillableUploadCount(v *int) *SharedLinkUpdate {
	if v != nil {
		_u.SetUploadCount(*v)
	}
	return _u
}

// AddUploadCount adds value to the "upload_count" field.
func (_u *SharedLinkUpdate) AddUploadCount(v int) *SharedLinkUpdate {
	_u.mutation.AddUploadCount(v)
	return _u
}

// SetActive sets the "active" field.
func (_u *SharedLinkUpdate) SetActive(v bool) *SharedLinkUpdate {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *SharedLinkUpdate) SetNillableActive(v *bool) *SharedLinkUpdate {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// SetWorkspace sets the "workspace" edge to the Workspace entity.
func (_u *SharedLinkUpdate) SetWorkspace(v *Workspace) *SharedLinkUpdate {
	return _u.SetWorkspaceID(v.ID)
}

// Mutation returns the SharedLinkMutation object of the builder.
func (_u *SharedLinkUpdate) Mutation() *SharedLinkMutation {
	return _u.mutation
}

// ClearWorkspace clears the "workspace" edge to the Workspace entity.
func (_u *SharedLinkUpdate) ClearWorkspace() *SharedLinkUpdate {
	_u.mutation.ClearWorkspace()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SharedLinkUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SharedLinkUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SharedLinkUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SharedLinkUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SharedLinkUpdate) check() error {
	if _u.mutation.WorkspaceCleared() && len(_u.mutation.WorkspaceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SharedLink.workspace"`)
	}
	return nil
}

func (_u *SharedLinkUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sharedlink.Table, sharedlink.Columns, sqlgraph.NewFieldSpec(sharedlink.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.FileNodeID(); ok {
		_spec.SetField(sharedlink.FieldFileNodeID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Permissions(); ok {
		_spec.SetField(sharedlink.FieldPermissions, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(sharedlink.FieldPasswordHash, field.TypeString, value)
	}
	if _u.mutation.PasswordHashCleared() {
		_spec.ClearField(sharedlink.FieldPasswordHash, field.TypeString)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(sharedlink.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(sharedlink.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.MaxUploads(); ok {
		_spec.SetField(sharedlink.FieldMaxUploads, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxUploads(); ok {
		_spec.AddField(sharedlink.FieldMaxUploads, field.TypeInt, value)
	}
	if _u.mutation.MaxUploadsCleared() {
		_spec.ClearField(sharedlink.FieldMaxUploads, field.TypeInt)
	}
	if value, ok := _u.mutation.UploadCount(); ok {
		_spec.SetField(sharedlink.FieldUploadCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUploadCount(); ok {
		_spec.AddField(sharedlink.FieldUploadCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(sharedlink.FieldActive, field.TypeBool, value)
	}
	if _u.mutation.WorkspaceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sharedlink.WorkspaceTable,
			Columns: []string{sharedlink.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WorkspaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sharedlink.WorkspaceTable,
			Columns: []string{sharedlink.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sharedlink.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SharedLinkUpdateOne is the builder for updating a single SharedLink entity.
type SharedLinkUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SharedLinkMutation
}

// SetWorkspaceID sets the "workspace_id" field.
func (_u *SharedLinkUpdateOne) SetWorkspaceID(v uuid.UUID) *SharedLinkUpdateOne {
	_u.mutation.SetWorkspaceID(v)
	return _u
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (_u *SharedLinkUpdateOne) SetNillableWorkspaceID(v *uuid.UUID) *SharedLinkUpdateOne {
	if v != nil {
		_u.SetWorkspaceID(*v)
	}
	return _u
}

// SetFileNodeID sets the "file_node_id" field.
func (_u *SharedLinkUpdateOne) SetFileNodeID(v uuid.UUID) *SharedLinkUpdateOne {
	_u.mutation.SetFileNodeID(v)
	return _u
}

// SetNillableFileNodeID sets the "file_node_id" field if the given value is not nil.
func (_u *SharedLinkUpdateOne) SetNillableFileNodeID(v *uuid.UUID) *SharedLinkUpdateOne {
	if v != nil {
		_u.SetFileNodeID(*v)
	}
	return _u
}

// SetPermissions sets the "permissions" field.
func (_u *SharedLinkUpdateOne) SetPermissions(v schema.SharedLinkPermissions) *SharedLinkUpdateOne {
	_u.mutation.SetPermissions(v)
	return _u
}

// SetNillablePermissions sets the "permissions" field if the given value is not nil.
func (_u *SharedLinkUpdateOne) SetNillablePermissions(v *schema.SharedLinkPermissions) *SharedLinkUpdateOne {
	if v != nil {
		_u.SetPermissions(*v)
	}
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *SharedLinkUpdateOne) SetPasswordHash(v string) *SharedLinkUpdateOne {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *SharedLinkUpdateOne) SetNillablePasswordHash(v *string) *SharedLinkUpdateOne {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// ClearPasswordHash clears the value of the "password_hash" field.
func (_u *SharedLinkUpdateOne) ClearPasswordHash() *SharedLinkUpdateOne {
	_u.mutation.ClearPasswordHash()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *SharedLinkUpdateOne) SetExpiresAt(v time.Time) *SharedLinkUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *SharedLinkUpdateOne) SetNillableExpiresAt(v *time.Time) *SharedLinkUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *SharedLinkUpdateOne) ClearExpiresAt() *SharedLinkUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetMaxUploads sets the "max_uploads" field.
func (_u *SharedLinkUpdateOne) SetMaxUploads(v int) *SharedLinkUpdateOne {
	_u.mutation.ResetMaxUploads()
	_u.mutation.SetMaxUploads(v)
	return _u
}

// SetNillableMaxUploads sets the "max_uploads" field if the given value is not nil.
func (_u *SharedLinkUpdateOne) SetNillableMaxUploads(v *int) *SharedLinkUpdateOne {
	if v != nil {
		_u.SetMaxUploads(*v)
	}
	return _u
}

// AddMaxUploads adds value to the "max_uploads" field.
func (_u *SharedLinkUpdateOne) AddMaxUploads(v int) *SharedLinkUpdateOne {
	_u.mutation.AddMaxUploads(v)
	return _u
}

// ClearMaxUploads clears the value of the "max_uploads" field.
func (_u *SharedLinkUpdateOne) ClearMaxUploads() *SharedLinkUpdateOne {
	_u.mutation.ClearMaxUploads()
	return _u
}

// SetUploadCount sets the "upload_count" field.
func (_u *SharedLinkUpdateOne) SetUploadCount(v int) *SharedLinkUpdateOne {
	_u.mutation.ResetUploadCount()
	_u.mutation.SetUploadCount(v)
	return _u
}

// SetNillableUploadCount sets the "upload_count" field if the given value is not nil.
func (_u *SharedLinkUpdateOne) SetNillableUploadCount(v *int) *SharedLinkUpdateOne {
	if v != nil {
		_u.SetUploadCount(*v)
	}
	return _u
}

// AddUploadCount adds value to the "upload_count" field.
func (_u *SharedLinkUpdateOne) AddUploadCount(v int) *SharedLinkUpdateOne {
	_u.mutation.AddUploadCount(v)
	return _u
}

// SetActive sets the "active" field.
func (_u *SharedLinkUpdateOne) SetActive(v bool) *SharedLinkUpdateOne {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *SharedLinkUpdateOne) SetNillableActive(v *bool) *SharedLinkUpdateOne {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// SetWorkspace sets the "workspace" edge to the Workspace entity.
func (_u *SharedLinkUpdateOne) SetWorkspace(v *Workspace) *SharedLinkUpdateOne {
	return _u.SetWorkspaceID(v.ID)
}

// Mutation returns the SharedLinkMutation object of the builder.
func (_u *SharedLinkUpdateOne) Mutation() *SharedLinkMutation {
	return _u.mutation
}

// ClearWorkspace clears the "workspace" edge to the Workspace entity.
func (_u *SharedLinkUpdateOne) ClearWorkspace() *SharedLinkUpdateOne {
	_u.mutation.ClearWorkspace()
	return _u
}

// Where appends a list predicates to the SharedLinkUpdate builder.
func (_u *SharedLinkUpdateOne) Where(ps ...predicate.SharedLink) *SharedLinkUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SharedLinkUpdateOne) Select(field string, fields ...string) *SharedLinkUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SharedLink entity.
func (_u *SharedLinkUpdateOne) Save(ctx context.Context) (*SharedLink, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SharedLinkUpdateOne) SaveX(ctx context.Context) *SharedLink {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SharedLinkUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SharedLinkUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SharedLinkUpdateOne) check() error {
	if _u.mutation.WorkspaceCleared() && len(_u.mutation.WorkspaceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SharedLink.workspace"`)
	}
	return nil
}

func (_u *SharedLinkUpdateOne) sqlSave(ctx context.Context) (_node *SharedLink, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sharedlink.Table, sharedlink.Columns, sqlgraph.NewFieldSpec(sharedlink.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SharedLink.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sharedlink.FieldID)
		for _, f := range fields {
			if !sharedlink.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sharedlink.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.FileNodeID(); ok {
		_spec.SetField(sharedlink.FieldFileNodeID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Permissions(); ok {
		_spec.SetField(sharedlink.FieldPermissions, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(sharedlink.FieldPasswordHash, field.TypeString, value)
	}
	if _u.mutation.PasswordHashCleared() {
		_spec.ClearField(sharedlink.FieldPasswordHash, field.TypeString)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(sharedlink.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(sharedlink.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.MaxUploads(); ok {
		_spec.SetField(sharedlink.FieldMaxUploads, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxUploads(); ok {
		_spec.AddField(sharedlink.FieldMaxUploads, field.TypeInt, value)
	}
	if _u.mutation.MaxUploadsCleared() {
		_spec.ClearField(sharedlink.FieldMaxUploads, field.TypeInt)
	}
	if value, ok := _u.mutation.UploadCount(); ok {
		_spec.SetField(sharedlink.FieldUploadCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUploadCount(); ok {
		_spec.AddField(sharedlink.FieldUploadCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(sharedlink.FieldActive, field.TypeBool, value)
	}
	if _u.mutation.WorkspaceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sharedlink.WorkspaceTable,
			Columns: []string{sharedlink.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WorkspaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sharedlink.WorkspaceTable,
			Columns: []string{sharedlink.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SharedLink{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sharedlink.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
