// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/drivebase/drivebase/internal/ent/schema"
	"github.com/drivebase/drivebase/internal/ent/sharedlink"
	"github.com/drivebase/drivebase/internal/ent/user"
	"github.com/google/uuid"
)

// SharedLinkCreate is the builder for creating a SharedLink entity.
type SharedLinkCreate struct {
	config
	mutation *SharedLinkMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *SharedLinkCreate) SetUserID(v uuid.UUID) *SharedLinkCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetFileNodeID sets the "file_node_id" field.
func (_c *SharedLinkCreate) SetFileNodeID(v uuid.UUID) *SharedLinkCreate {
	_c.mutation.SetFileNodeID(v)
	return _c
}

// SetToken sets the "token" field.
func (_c *SharedLinkCreate) SetToken(v string) *SharedLinkCreate {
	_c.mutation.SetToken(v)
	return _c
}

// SetPermissions sets the "permissions" field.
func (_c *SharedLinkCreate) SetPermissions(v schema.SharedLinkPermissions) *SharedLinkCreate {
	_c.mutation.SetPermissions(v)
	return _c
}

// SetPasswordHash sets the "password_hash" field.
func (_c *SharedLinkCreate) SetPasswordHash(v string) *SharedLinkCreate {
	_c.mutation.SetPasswordHash(v)
	return _c
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_c *SharedLinkCreate) SetNillablePasswordHash(v *string) *SharedLinkCreate {
	if v != nil {
		_c.SetPasswordHash(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *SharedLinkCreate) SetExpiresAt(v time.Time) *SharedLinkCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *SharedLinkCreate) SetNillableExpiresAt(v *time.Time) *SharedLinkCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetMaxUploads sets the "max_uploads" field.
func (_c *SharedLinkCreate) SetMaxUploads(v int) *SharedLinkCreate {
	_c.mutation.SetMaxUploads(v)
	return _c
}

// SetNillableMaxUploads sets the "max_uploads" field if the given value is not nil.
func (_c *SharedLinkCreate) SetNillableMaxUploads(v *int) *SharedLinkCreate {
	if v != nil {
		_c.SetMaxUploads(*v)
	}
	return _c
}

// SetUploadCount sets the "upload_count" field.
func (_c *SharedLinkCreate) SetUploadCount(v int) *SharedLinkCreate {
	_c.mutation.SetUploadCount(v)
	return _c
}

// SetNillableUploadCount sets the "upload_count" field if the given value is not nil.
func (_c *SharedLinkCreate) SetNillableUploadCount(v *int) *SharedLinkCreate {
	if v != nil {
		_c.SetUploadCount(*v)
	}
	return _c
}

// SetActive sets the "active" field.
func (_c *SharedLinkCreate) SetActive(v bool) *SharedLinkCreate {
	_c.mutation.SetActive(v)
	return _c
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_c *SharedLinkCreate) SetNillableActive(v *bool) *SharedLinkCreate {
	if v != nil {
		_c.SetActive(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SharedLinkCreate) SetCreatedAt(v time.Time) *SharedLinkCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SharedLinkCreate) SetNillableCreatedAt(v *time.Time) *SharedLinkCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SharedLinkCreate) SetID(v uuid.UUID) *SharedLinkCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *SharedLinkCreate) SetNillableID(v *uuid.UUID) *SharedLinkCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *SharedLinkCreate) SetUser(v *User) *SharedLinkCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the SharedLinkMutation object of the builder.
func (_c *SharedLinkCreate) Mutation() *SharedLinkMutation {
	return _c.mutation
}

// Save creates the SharedLink in the database.
func (_c *SharedLinkCreate) Save(ctx context.Context) (*SharedLink, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SharedLinkCreate) SaveX(ctx context.Context) *SharedLink {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SharedLinkCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SharedLinkCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SharedLinkCreate) defaults() {
	if _, ok := _c.mutation.UploadCount(); !ok {
		v := sharedlink.DefaultUploadCount
		_c.mutation.SetUploadCount(v)
	}
	if _, ok := _c.mutation.Active(); !ok {
		v := sharedlink.DefaultActive
		_c.mutation.SetActive(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := sharedlink.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := sharedlink.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SharedLinkCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "SharedLink.user_id"`)}
	}
	if _, ok := _c.mutation.FileNodeID(); !ok {
		return &ValidationError{Name: "file_node_id", err: errors.New(`ent: missing required field "SharedLink.file_node_id"`)}
	}
	if _, ok := _c.mutation.Token(); !ok {
		return &ValidationError{Name: "token", err: errors.New(`ent: missing required field "SharedLink.token"`)}
	}
	if v, ok := _c.mutation.Token(); ok {
		if err := sharedlink.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "SharedLink.token": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Permissions(); !ok {
		return &ValidationError{Name: "permissions", err: errors.New(`ent: missing required field "SharedLink.permissions"`)}
	}
	if _, ok := _c.mutation.UploadCount(); !ok {
		return &ValidationError{Name: "upload_count", err: errors.New(`ent: missing required field "SharedLink.upload_count"`)}
	}
	if _, ok := _c.mutation.Active(); !ok {
		return &ValidationError{Name: "active", err: errors.New(`ent: missing required field "SharedLink.active"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SharedLink.created_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "SharedLink.user"`)}
	}
	return nil
}

func (_c *SharedLinkCreate) sqlSave(ctx context.Context) (*SharedLink, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SharedLinkCreate) createSpec() (*SharedLink, *sqlgraph.CreateSpec) {
	var (
		_node = &SharedLink{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(sharedlink.Table, sqlgraph.NewFieldSpec(sharedlink.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.FileNodeID(); ok {
		_spec.SetField(sharedlink.FieldFileNodeID, field.TypeUUID, value)
		_node.FileNodeID = value
	}
	if value, ok := _c.mutation.Token(); ok {
		_spec.SetField(sharedlink.FieldToken, field.TypeString, value)
		_node.Token = value
	}
	if value, ok := _c.mutation.Permissions(); ok {
		_spec.SetField(sharedlink.FieldPermissions, field.TypeJSON, value)
		_node.Permissions = value
	}
	if value, ok := _c.mutation.PasswordHash(); ok {
		_spec.SetField(sharedlink.FieldPasswordHash, field.TypeString, value)
		_node.PasswordHash = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(sharedlink.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := _c.mutation.MaxUploads(); ok {
		_spec.SetField(sharedlink.FieldMaxUploads, field.TypeInt, value)
		_node.MaxUploads = &value
	}
	if value, ok := _c.mutation.UploadCount(); ok {
		_spec.SetField(sharedlink.FieldUploadCount, field.TypeInt, value)
		_node.UploadCount = value
	}
	if value, ok := _c.mutation.Active(); ok {
		_spec.SetField(sharedlink.FieldActive, field.TypeBool, value)
		_node.Active = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(sharedlink.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sharedlink.UserTable,
			Columns: []string{sharedlink.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SharedLinkCreateBulk is the builder for creating many SharedLink entities in bulk.
type SharedLinkCreateBulk struct {
	config
	err      error
	builders []*SharedLinkCreate
}

// Save creates the SharedLink entities in the database.
func (_c *SharedLinkCreateBulk) Save(ctx context.Context) ([]*SharedLink, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SharedLink, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SharedLinkMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SharedLinkCreateBulk) SaveX(ctx context.Context) []*SharedLink {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SharedLinkCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SharedLinkCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
