// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/drivebase/drivebase/internal/ent/transferjob"
	"github.com/drivebase/drivebase/internal/ent/transferjobfile"
	"github.com/google/uuid"
)

// TransferJobFile is the model entity for the TransferJobFile schema.
type TransferJobFile struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// JobID holds the value of the "job_id" field.
	JobID uuid.UUID `json:"job_id,omitempty"`
	// SourceRemoteID holds the value of the "source_remote_id" field.
	SourceRemoteID string `json:"source_remote_id,omitempty"`
	// DestRemoteID holds the value of the "dest_remote_id" field.
	DestRemoteID string `json:"dest_remote_id,omitempty"`
	// FileName holds the value of the "file_name" field.
	FileName string `json:"file_name,omitempty"`
	// Size holds the value of the "size" field.
	Size int64 `json:"size,omitempty"`
	// TransferredBytes holds the value of the "transferred_bytes" field.
	TransferredBytes int64 `json:"transferred_bytes,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage string `json:"error_message,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// CompletedAt holds the value of the "completed_at" field.
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TransferJobFileQuery when eager-loading is set.
	Edges        TransferJobFileEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TransferJobFileEdges holds the relations/edges for other nodes in the graph.
type TransferJobFileEdges struct {
	// Job holds the value of the job edge.
	Job *TransferJob `json:"job,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// JobOrErr returns the Job value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TransferJobFileEdges) JobOrErr() (*TransferJob, error) {
	if e.Job != nil {
		return e.Job, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: transferjob.Label}
	}
	return nil, &NotLoadedError{edge: "job"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TransferJobFile) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case transferjobfile.FieldSize, transferjobfile.FieldTransferredBytes:
			values[i] = new(sql.NullInt64)
		case transferjobfile.FieldSourceRemoteID, transferjobfile.FieldDestRemoteID, transferjobfile.FieldFileName, transferjobfile.FieldStatus, transferjobfile.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case transferjobfile.FieldCreatedAt, transferjobfile.FieldCompletedAt:
			values[i] = new(sql.NullTime)
		case transferjobfile.FieldID, transferjobfile.FieldJobID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TransferJobFile fields.
func (_m *TransferJobFile) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case transferjobfile.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case transferjobfile.FieldJobID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field job_id", values[i])
			} else if value != nil {
				_m.JobID = *value
			}
		case transferjobfile.FieldSourceRemoteID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_remote_id", values[i])
			} else if value.Valid {
				_m.SourceRemoteID = value.String
			}
		case transferjobfile.FieldDestRemoteID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field dest_remote_id", values[i])
			} else if value.Valid {
				_m.DestRemoteID = value.String
			}
		case transferjobfile.FieldFileName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field file_name", values[i])
			} else if value.Valid {
				_m.FileName = value.String
			}
		case transferjobfile.FieldSize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field size", values[i])
			} else if value.Valid {
				_m.Size = value.Int64
			}
		case transferjobfile.FieldTransferredBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field transferred_bytes", values[i])
			} else if value.Valid {
				_m.TransferredBytes = value.Int64
			}
		case transferjobfile.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case transferjobfile.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = value.String
			}
		case transferjobfile.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case transferjobfile.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				_m.CompletedAt = new(time.Time)
				*_m.CompletedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TransferJobFile.
// This includes values selected through modifiers, order, etc.
func (_m *TransferJobFile) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryJob queries the "job" edge of the TransferJobFile entity.
func (_m *TransferJobFile) QueryJob() *TransferJobQuery {
	return NewTransferJobFileClient(_m.config).QueryJob(_m)
}

// Update returns a builder for updating this TransferJobFile.
// Note that you need to call TransferJobFile.Unwrap() before calling this method if this TransferJobFile
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TransferJobFile) Update() *TransferJobFileUpdateOne {
	return NewTransferJobFileClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TransferJobFile entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TransferJobFile) Unwrap() *TransferJobFile {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TransferJobFile is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TransferJobFile) String() string {
	var builder strings.Builder
	builder.WriteString("TransferJobFile(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("job_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.JobID))
	builder.WriteString(", ")
	builder.WriteString("source_remote_id=")
	builder.WriteString(_m.SourceRemoteID)
	builder.WriteString(", ")
	builder.WriteString("dest_remote_id=")
	builder.WriteString(_m.DestRemoteID)
	builder.WriteString(", ")
	builder.WriteString("file_name=")
	builder.WriteString(_m.FileName)
	builder.WriteString(", ")
	builder.WriteString("size=")
	builder.WriteString(fmt.Sprintf("%v", _m.Size))
	builder.WriteString(", ")
	builder.WriteString("transferred_bytes=")
	builder.WriteString(fmt.Sprintf("%v", _m.TransferredBytes))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("error_message=")
	builder.WriteString(_m.ErrorMessage)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.CompletedAt; v != nil {
		builder.WriteString("completed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// TransferJobFiles is a parsable slice of TransferJobFile.
type TransferJobFiles []*TransferJobFile
