// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/drivebase/drivebase/internal/ent/predicate"
	"github.com/drivebase/drivebase/internal/ent/transferjob"
	"github.com/drivebase/drivebase/internal/ent/transferjobfile"
	"github.com/google/uuid"
)

// TransferJobFileUpdate is the builder for updating TransferJobFile entities.
type TransferJobFileUpdate struct {
	config
	hooks    []Hook
	mutation *TransferJobFileMutation
}

// Where appends a list predicates to the TransferJobFileUpdate builder.
func (_u *TransferJobFileUpdate) Where(ps ...predicate.TransferJobFile) *TransferJobFileUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetJobID sets the "job_id" field.
func (_u *TransferJobFileUpdate) SetJobID(v uuid.UUID) *TransferJobFileUpdate {
	_u.mutation.SetJobID(v)
	return _u
}

// SetNillableJobID sets the "job_id" field if the given value is not nil.
func (_u *TransferJobFileUpdate) SetNillableJobID(v *uuid.UUID) *TransferJobFileUpdate {
	if v != nil {
		_u.SetJobID(*v)
	}
	return _u
}

// SetSourceRemoteID sets the "source_remote_id" field.
func (_u *TransferJobFileUpdate) SetSourceRemoteID(v string) *TransferJobFileUpdate {
	_u.mutation.SetSourceRemoteID(v)
	return _u
}

// SetNillableSourceRemoteID sets the "source_remote_id" field if the given value is not nil.
func (_u *TransferJobFileUpdate) SetNillableSourceRemoteID(v *string) *TransferJobFileUpdate {
	if v != nil {
		_u.SetSourceRemoteID(*v)
	}
	return _u
}

// SetDestRemoteID sets the "dest_remote_id" field.
func (_u *TransferJobFileUpdate) SetDestRemoteID(v string) *TransferJobFileUpdate {
	_u.mutation.SetDestRemoteID(v)
	return _u
}

// SetNillableDestRemoteID sets the "dest_remote_id" field if the given value is not nil.
func (_u *TransferJobFileUpdate) SetNillableDestRemoteID(v *string) *TransferJobFileUpdate {
	if v != nil {
		_u.SetDestRemoteID(*v)
	}
	return _u
}

// ClearDestRemoteID clears the value of the "dest_remote_id" field.
func (_u *TransferJobFileUpdate) ClearDestRemoteID() *TransferJobFileUpdate {
	_u.mutation.ClearDestRemoteID()
	return _u
}

// SetFileName sets the "file_name" field.
func (_u *TransferJobFileUpdate) SetFileName(v string) *TransferJobFileUpdate {
	_u.mutation.SetFileName(v)
	return _u
}

// SetNillableFileName sets the "file_name" field if the given value is not nil.
func (_u *TransferJobFileUpdate) SetNillableFileName(v *string) *TransferJobFileUpdate {
	if v != nil {
		_u.SetFileName(*v)
	}
	return _u
}

// SetSize sets the "size" field.
func (_u *TransferJobFileUpdate) SetSize(v int64) *TransferJobFileUpdate {
	_u.mutation.ResetSize()
	_u.mutation.SetSize(v)
	return _u
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_u *TransferJobFileUpdate) SetNillableSize(v *int64) *TransferJobFileUpdate {
	if v != nil {
		_u.SetSize(*v)
	}
	return _u
}

// AddSize adds value to the "size" field.
func (_u *TransferJobFileUpdate) AddSize(v int64) *TransferJobFileUpdate {
	_u.mutation.AddSize(v)
	return _u
}

// SetTransferredBytes sets the "transferred_bytes" field.
func (_u *TransferJobFileUpdate) SetTransferredBytes(v int64) *TransferJobFileUpdate {
	_u.mutation.ResetTransferredBytes()
	_u.mutation.SetTransferredBytes(v)
	return _u
}

// SetNillableTransferredBytes sets the "transferred_bytes" field if the given value is not nil.
func (_u *TransferJobFileUpdate) SetNillableTransferredBytes(v *int64) *TransferJobFileUpdate {
	if v != nil {
		_u.SetTransferredBytes(*v)
	}
	return _u
}

// AddTransferredBytes adds value to the "transferred_bytes" field.
func (_u *TransferJobFileUpdate) AddTransferredBytes(v int64) *TransferJobFileUpdate {
	_u.mutation.AddTransferredBytes(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *TransferJobFileUpdate) SetStatus(v string) *TransferJobFileUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TransferJobFileUpdate) SetNillableStatus(v *string) *TransferJobFileUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *TransferJobFileUpdate) SetErrorMessage(v string) *TransferJobFileUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *TransferJobFileUpdate) SetNillableErrorMessage(v *string) *TransferJobFileUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *TransferJobFileUpdate) ClearErrorMessage() *TransferJobFileUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *TransferJobFileUpdate) SetCompletedAt(v time.Time) *TransferJobFileUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *TransferJobFileUpdate) SetNillableCompletedAt(v *time.Time) *TransferJobFileUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *TransferJobFileUpdate) ClearCompletedAt() *TransferJobFileUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetJob sets the "job" edge to the TransferJob entity.
func (_u *TransferJobFileUpdate) SetJob(v *TransferJob) *TransferJobFileUpdate {
	return _u.SetJobID(v.ID)
}

// Mutation returns the TransferJobFileMutation object of the builder.
func (_u *TransferJobFileUpdate) Mutation() *TransferJobFileMutation {
	return _u.mutation
}

// ClearJob clears the "job" edge to the TransferJob entity.
func (_u *TransferJobFileUpdate) ClearJob() *TransferJobFileUpdate {
	_u.mutation.ClearJob()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TransferJobFileUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TransferJobFileUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TransferJobFileUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TransferJobFileUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TransferJobFileUpdate) check() error {
	if v, ok := _u.mutation.SourceRemoteID(); ok {
		if err := transferjobfile.SourceRemoteIDValidator(v); err != nil {
			return &ValidationError{Name: "source_remote_id", err: fmt.Errorf(`ent: validator failed for field "TransferJobFile.source_remote_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileName(); ok {
		if err := transferjobfile.FileNameValidator(v); err != nil {
			return &ValidationError{Name: "file_name", err: fmt.Errorf(`ent: validator failed for field "TransferJobFile.file_name": %w`, err)}
		}
	}
	if _u.mutation.JobCleared() && len(_u.mutation.JobIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TransferJobFile.job"`)
	}
	return nil
}

func (_u *TransferJobFileUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(transferjobfile.Table, transferjobfile.Columns, sqlgraph.NewFieldSpec(transferjobfile.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SourceRemoteID(); ok {
		_spec.SetField(transferjobfile.FieldSourceRemoteID, field.TypeString, value)
	}
	if value, ok := _u.mutation.DestRemoteID(); ok {
		_spec.SetField(transferjobfile.FieldDestRemoteID, field.TypeString, value)
	}
	if _u.mutation.DestRemoteIDCleared() {
		_spec.ClearField(transferjobfile.FieldDestRemoteID, field.TypeString)
	}
	if value, ok := _u.mutation.FileName(); ok {
		_spec.SetField(transferjobfile.FieldFileName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Size(); ok {
		_spec.SetField(transferjobfile.FieldSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSize(); ok {
		_spec.AddField(transferjobfile.FieldSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TransferredBytes(); ok {
		_spec.SetField(transferjobfile.FieldTransferredBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTransferredBytes(); ok {
		_spec.AddField(transferjobfile.FieldTransferredBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(transferjobfile.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(transferjobfile.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(transferjobfile.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(transferjobfile.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(transferjobfile.FieldCompletedAt, field.TypeTime)
	}
	if _u.mutation.JobCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transferjobfile.JobTable,
			Columns: []string{transferjobfile.JobColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transferjob.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.JobIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transferjobfile.JobTable,
			Columns: []string{transferjobfile.JobColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transferjob.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{transferjobfile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TransferJobFileUpdateOne is the builder for updating a single TransferJobFile entity.
type TransferJobFileUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TransferJobFileMutation
}

// SetJobID sets the "job_id" field.
func (_u *TransferJobFileUpdateOne) SetJobID(v uuid.UUID) *TransferJobFileUpdateOne {
	_u.mutation.SetJobID(v)
	return _u
}

// SetNillableJobID sets the "job_id" field if the given value is not nil.
func (_u *TransferJobFileUpdateOne) SetNillableJobID(v *uuid.UUID) *TransferJobFileUpdateOne {
	if v != nil {
		_u.SetJobID(*v)
	}
	return _u
}

// SetSourceRemoteID sets the "source_remote_id" field.
func (_u *TransferJobFileUpdateOne) SetSourceRemoteID(v string) *TransferJobFileUpdateOne {
	_u.mutation.SetSourceRemoteID(v)
	return _u
}

// SetNillableSourceRemoteID sets the "source_remote_id" field if the given value is not nil.
func (_u *TransferJobFileUpdateOne) SetNillableSourceRemoteID(v *string) *TransferJobFileUpdateOne {
	if v != nil {
		_u.SetSourceRemoteID(*v)
	}
	return _u
}

// SetDestRemoteID sets the "dest_remote_id" field.
func (_u *TransferJobFileUpdateOne) SetDestRemoteID(v string) *TransferJobFileUpdateOne {
	_u.mutation.SetDestRemoteID(v)
	return _u
}

// SetNillableDestRemoteID sets the "dest_remote_id" field if the given value is not nil.
func (_u *TransferJobFileUpdateOne) SetNillableDestRemoteID(v *string) *TransferJobFileUpdateOne {
	if v != nil {
		_u.SetDestRemoteID(*v)
	}
	return _u
}

// ClearDestRemoteID clears the value of the "dest_remote_id" field.
func (_u *TransferJobFileUpdateOne) ClearDestRemoteID() *TransferJobFileUpdateOne {
	_u.mutation.ClearDestRemoteID()
	return _u
}

// SetFileName sets the "file_name" field.
func (_u *TransferJobFileUpdateOne) SetFileName(v string) *TransferJobFileUpdateOne {
	_u.mutation.SetFileName(v)
	return _u
}

// SetNillableFileName sets the "file_name" field if the given value is not nil.
func (_u *TransferJobFileUpdateOne) SetNillableFileName(v *string) *TransferJobFileUpdateOne {
	if v != nil {
		_u.SetFileName(*v)
	}
	return _u
}

// SetSize sets the "size" field.
func (_u *TransferJobFileUpdateOne) SetSize(v int64) *TransferJobFileUpdateOne {
	_u.mutation.ResetSize()
	_u.mutation.SetSize(v)
	return _u
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_u *TransferJobFileUpdateOne) SetNillableSize(v *int64) *TransferJobFileUpdateOne {
	if v != nil {
		_u.SetSize(*v)
	}
	return _u
}

// AddSize adds value to the "size" field.
func (_u *TransferJobFileUpdateOne) AddSize(v int64) *TransferJobFileUpdateOne {
	_u.mutation.AddSize(v)
	return _u
}

// SetTransferredBytes sets the "transferred_bytes" field.
func (_u *TransferJobFileUpdateOne) SetTransferredBytes(v int64) *TransferJobFileUpdateOne {
	_u.mutation.ResetTransferredBytes()
	_u.mutation.SetTransferredBytes(v)
	return _u
}

// SetNillableTransferredBytes sets the "transferred_bytes" field if the given value is not nil.
func (_u *TransferJobFileUpdateOne) SetNillableTransferredBytes(v *int64) *TransferJobFileUpdateOne {
	if v != nil {
		_u.SetTransferredBytes(*v)
	}
	return _u
}

// AddTransferredBytes adds value to the "transferred_bytes" field.
func (_u *TransferJobFileUpdateOne) AddTransferredBytes(v int64) *TransferJobFileUpdateOne {
	_u.mutation.AddTransferredBytes(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *TransferJobFileUpdateOne) SetStatus(v string) *TransferJobFileUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TransferJobFileUpdateOne) SetNillableStatus(v *string) *TransferJobFileUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *TransferJobFileUpdateOne) SetErrorMessage(v string) *TransferJobFileUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *TransferJobFileUpdateOne) SetNillableErrorMessage(v *string) *TransferJobFileUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *TransferJobFileUpdateOne) ClearErrorMessage() *TransferJobFileUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *TransferJobFileUpdateOne) SetCompletedAt(v time.Time) *TransferJobFileUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *TransferJobFileUpdateOne) SetNillableCompletedAt(v *time.Time) *TransferJobFileUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *TransferJobFileUpdateOne) ClearCompletedAt() *TransferJobFileUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetJob sets the "job" edge to the TransferJob entity.
func (_u *TransferJobFileUpdateOne) SetJob(v *TransferJob) *TransferJobFileUpdateOne {
	return _u.SetJobID(v.ID)
}

// Mutation returns the TransferJobFileMutation object of the builder.
func (_u *TransferJobFileUpdateOne) Mutation() *TransferJobFileMutation {
	return _u.mutation
}

// ClearJob clears the "job" edge to the TransferJob entity.
func (_u *TransferJobFileUpdateOne) ClearJob() *TransferJobFileUpdateOne {
	_u.mutation.ClearJob()
	return _u
}

// Where appends a list predicates to the TransferJobFileUpdate builder.
func (_u *TransferJobFileUpdateOne) Where(ps ...predicate.TransferJobFile) *TransferJobFileUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TransferJobFileUpdateOne) Select(field string, fields ...string) *TransferJobFileUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TransferJobFile entity.
func (_u *TransferJobFileUpdateOne) Save(ctx context.Context) (*TransferJobFile, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TransferJobFileUpdateOne) SaveX(ctx context.Context) *TransferJobFile {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TransferJobFileUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TransferJobFileUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TransferJobFileUpdateOne) check() error {
	if v, ok := _u.mutation.SourceRemoteID(); ok {
		if err := transferjobfile.SourceRemoteIDValidator(v); err != nil {
			return &ValidationError{Name: "source_remote_id", err: fmt.Errorf(`ent: validator failed for field "TransferJobFile.source_remote_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileName(); ok {
		if err := transferjobfile.FileNameValidator(v); err != nil {
			return &ValidationError{Name: "file_name", err: fmt.Errorf(`ent: validator failed for field "TransferJobFile.file_name": %w`, err)}
		}
	}
	if _u.mutation.JobCleared() && len(_u.mutation.JobIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TransferJobFile.job"`)
	}
	return nil
}

func (_u *TransferJobFileUpdateOne) sqlSave(ctx context.Context) (_node *TransferJobFile, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(transferjobfile.Table, transferjobfile.Columns, sqlgraph.NewFieldSpec(transferjobfile.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TransferJobFile.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, transferjobfile.FieldID)
		for _, f := range fields {
			if !transferjobfile.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != transferjobfile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SourceRemoteID(); ok {
		_spec.SetField(transferjobfile.FieldSourceRemoteID, field.TypeString, value)
	}
	if value, ok := _u.mutation.DestRemoteID(); ok {
		_spec.SetField(transferjobfile.FieldDestRemoteID, field.TypeString, value)
	}
	if _u.mutation.DestRemoteIDCleared() {
		_spec.ClearField(transferjobfile.FieldDestRemoteID, field.TypeString)
	}
	if value, ok := _u.mutation.FileName(); ok {
		_spec.SetField(transferjobfile.FieldFileName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Size(); ok {
		_spec.SetField(transferjobfile.FieldSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSize(); ok {
		_spec.AddField(transferjobfile.FieldSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TransferredBytes(); ok {
		_spec.SetField(transferjobfile.FieldTransferredBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTransferredBytes(); ok {
		_spec.AddField(transferjobfile.FieldTransferredBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(transferjobfile.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(transferjobfile.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(transferjobfile.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(transferjobfile.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(transferjobfile.FieldCompletedAt, field.TypeTime)
	}
	if _u.mutation.JobCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transferjobfile.JobTable,
			Columns: []string{transferjobfile.JobColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transferjob.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.JobIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transferjobfile.JobTable,
			Columns: []string{transferjobfile.JobColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transferjob.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TransferJobFile{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{transferjobfile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
