// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/drivebase/drivebase/internal/ent/predicate"
	"github.com/drivebase/drivebase/internal/ent/uploadbatch"
	"github.com/drivebase/drivebase/internal/ent/uploadbatchfile"
	"github.com/drivebase/drivebase/internal/ent/workspace"
	"github.com/google/uuid"
)

// UploadBatchQuery is the builder for querying UploadBatch entities.
type UploadBatchQuery struct {
	config
	ctx           *QueryContext
	order         []uploadbatch.OrderOption
	inters        []Interceptor
	predicates    []predicate.UploadBatch
	withWorkspace *WorkspaceQuery
	withFiles     *UploadBatchFileQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UploadBatchQuery builder.
func (_q *UploadBatchQuery) Where(ps ...predicate.UploadBatch) *UploadBatchQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *UploadBatchQuery) Limit(limit int) *UploadBatchQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *UploadBatchQuery) Offset(offset int) *UploadBatchQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *UploadBatchQuery) Unique(unique bool) *UploadBatchQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *UploadBatchQuery) Order(o ...uploadbatch.OrderOption) *UploadBatchQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryWorkspace chains the current query on the "workspace" edge.
func (_q *UploadBatchQuery) QueryWorkspace() *WorkspaceQuery {
	query := (&WorkspaceClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(uploadbatch.Table, uploadbatch.FieldID, selector),
			sqlgraph.To(workspace.Table, workspace.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, uploadbatch.WorkspaceTable, uploadbatch.WorkspaceColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryFiles chains the current query on the "files" edge.
func (_q *UploadBatchQuery) QueryFiles() *UploadBatchFileQuery {
	query := (&UploadBatchFileClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(uploadbatch.Table, uploadbatch.FieldID, selector),
			sqlgraph.To(uploadbatchfile.Table, uploadbatchfile.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, uploadbatch.FilesTable, uploadbatch.FilesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first UploadBatch entity from the query.
// Returns a *NotFoundError when no UploadBatch was found.
func (_q *UploadBatchQuery) First(ctx context.Context) (*UploadBatch, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{uploadbatch.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *UploadBatchQuery) FirstX(ctx context.Context) *UploadBatch {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UploadBatch ID from the query.
// Returns a *NotFoundError when no UploadBatch ID was found.
func (_q *UploadBatchQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{uploadbatch.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *UploadBatchQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UploadBatch entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UploadBatch entity is found.
// Returns a *NotFoundError when no UploadBatch entities are found.
func (_q *UploadBatchQuery) Only(ctx context.Context) (*UploadBatch, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{uploadbatch.Label}
	default:
		return nil, &NotSingularError{uploadbatch.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *UploadBatchQuery) OnlyX(ctx context.Context) *UploadBatch {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UploadBatch ID in the query.
// Returns a *NotSingularError when more than one UploadBatch ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *UploadBatchQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{uploadbatch.Label}
	default:
		err = &NotSingularError{uploadbatch.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *UploadBatchQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UploadBatches.
func (_q *UploadBatchQuery) All(ctx context.Context) ([]*UploadBatch, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*UploadBatch, *UploadBatchQuery]()
	return withInterceptors[[]*UploadBatch](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *UploadBatchQuery) AllX(ctx context.Context) []*UploadBatch {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UploadBatch IDs.
func (_q *UploadBatchQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(uploadbatch.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *UploadBatchQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *UploadBatchQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*UploadBatchQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *UploadBatchQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *UploadBatchQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *UploadBatchQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UploadBatchQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *UploadBatchQuery) Clone() *UploadBatchQuery {
	if _q == nil {
		return nil
	}
	return &UploadBatchQuery{
		config:        _q.config,
		ctx:           _q.ctx.Clone(),
		order:         append([]uploadbatch.OrderOption{}, _q.order...),
		inters:        append([]Interceptor{}, _q.inters...),
		predicates:    append([]predicate.UploadBatch{}, _q.predicates...),
		withWorkspace: _q.withWorkspace.Clone(),
		withFiles:     _q.withFiles.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithWorkspace tells the query-builder to eager-load the nodes that are connected to
// the "workspace" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *UploadBatchQuery) WithWorkspace(opts ...func(*WorkspaceQuery)) *UploadBatchQuery {
	query := (&WorkspaceClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withWorkspace = query
	return _q
}

// WithFiles tells the query-builder to eager-load the nodes that are connected to
// the "files" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *UploadBatchQuery) WithFiles(opts ...func(*UploadBatchFileQuery)) *UploadBatchQuery {
	query := (&UploadBatchFileClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withFiles = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		WorkspaceID uuid.UUID `json:"workspace_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UploadBatch.Query().
//		GroupBy(uploadbatch.FieldWorkspaceID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *UploadBatchQuery) GroupBy(field string, fields ...string) *UploadBatchGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UploadBatchGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = uploadbatch.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		WorkspaceID uuid.UUID `json:"workspace_id,omitempty"`
//	}
//
//	client.UploadBatch.Query().
//		Select(uploadbatch.FieldWorkspaceID).
//		Scan(ctx, &v)
func (_q *UploadBatchQuery) Select(fields ...string) *UploadBatchSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &UploadBatchSelect{UploadBatchQuery: _q}
	sbuild.label = uploadbatch.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UploadBatchSelect configured with the given aggregations.
func (_q *UploadBatchQuery) Aggregate(fns ...AggregateFunc) *UploadBatchSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *UploadBatchQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !uploadbatch.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *UploadBatchQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UploadBatch, error) {
	var (
		nodes       = []*UploadBatch{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withWorkspace != nil,
			_q.withFiles != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UploadBatch).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UploadBatch{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withWorkspace; query != nil {
		if err := _q.loadWorkspace(ctx, query, nodes, nil,
			func(n *UploadBatch, e *Workspace) { n.Edges.Workspace = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withFiles; query != nil {
		if err := _q.loadFiles(ctx, query, nodes,
			func(n *UploadBatch) { n.Edges.Files = []*UploadBatchFile{} },
			func(n *UploadBatch, e *UploadBatchFile) { n.Edges.Files = append(n.Edges.Files, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *UploadBatchQuery) loadWorkspace(ctx context.Context, query *WorkspaceQuery, nodes []*UploadBatch, init func(*UploadBatch), assign func(*UploadBatch, *Workspace)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*UploadBatch)
	for i := range nodes {
		fk := nodes[i].WorkspaceID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(workspace.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "workspace_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *UploadBatchQuery) loadFiles(ctx context.Context, query *UploadBatchFileQuery, nodes []*UploadBatch, init func(*UploadBatch), assign func(*UploadBatch, *UploadBatchFile)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*UploadBatch)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(uploadbatchfile.FieldBatchID)
	}
	query.Where(predicate.UploadBatchFile(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(uploadbatch.FilesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.BatchID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "batch_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *UploadBatchQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *UploadBatchQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(uploadbatch.Table, uploadbatch.Columns, sqlgraph.NewFieldSpec(uploadbatch.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, uploadbatch.FieldID)
		for i := range fields {
			if fields[i] != uploadbatch.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withWorkspace != nil {
			_spec.Node.AddColumnOnce(uploadbatch.FieldWorkspaceID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *UploadBatchQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(uploadbatch.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = uploadbatch.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UploadBatchGroupBy is the group-by builder for UploadBatch entities.
type UploadBatchGroupBy struct {
	selector
	build *UploadBatchQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *UploadBatchGroupBy) Aggregate(fns ...AggregateFunc) *UploadBatchGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *UploadBatchGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UploadBatchQuery, *UploadBatchGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *UploadBatchGroupBy) sqlScan(ctx context.Context, root *UploadBatchQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UploadBatchSelect is the builder for selecting fields of UploadBatch entities.
type UploadBatchSelect struct {
	*UploadBatchQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *UploadBatchSelect) Aggregate(fns ...AggregateFunc) *UploadBatchSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *UploadBatchSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UploadBatchQuery, *UploadBatchSelect](ctx, _s.UploadBatchQuery, _s, _s.inters, v)
}

func (_s *UploadBatchSelect) sqlScan(ctx context.Context, root *UploadBatchQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
