// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/drivebase/drivebase/internal/ent/uploadbatch"
	"github.com/drivebase/drivebase/internal/ent/workspace"
	"github.com/google/uuid"
)

// UploadBatch is the model entity for the UploadBatch schema.
type UploadBatch struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// WorkspaceID holds the value of the "workspace_id" field.
	WorkspaceID uuid.UUID `json:"workspace_id,omitempty"`
	// ProviderID holds the value of the "provider_id" field.
	ProviderID uuid.UUID `json:"provider_id,omitempty"`
	// ParentRemoteID holds the value of the "parent_remote_id" field.
	ParentRemoteID string `json:"parent_remote_id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// TotalFiles holds the value of the "total_files" field.
	TotalFiles int `json:"total_files,omitempty"`
	// CompletedFiles holds the value of the "completed_files" field.
	CompletedFiles int `json:"completed_files,omitempty"`
	// FailedFiles holds the value of the "failed_files" field.
	FailedFiles int `json:"failed_files,omitempty"`
	// TotalBytes holds the value of the "total_bytes" field.
	TotalBytes int64 `json:"total_bytes,omitempty"`
	// TransferredBytes holds the value of the "transferred_bytes" field.
	TransferredBytes int64 `json:"transferred_bytes,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// CompletedAt holds the value of the "completed_at" field.
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UploadBatchQuery when eager-loading is set.
	Edges        UploadBatchEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UploadBatchEdges holds the relations/edges for other nodes in the graph.
type UploadBatchEdges struct {
	// Workspace holds the value of the workspace edge.
	Workspace *Workspace `json:"workspace,omitempty"`
	// Files holds the value of the files edge.
	Files []*UploadBatchFile `json:"files,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// WorkspaceOrErr returns the Workspace value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UploadBatchEdges) WorkspaceOrErr() (*Workspace, error) {
	if e.Workspace != nil {
		return e.Workspace, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: workspace.Label}
	}
	return nil, &NotLoadedError{edge: "workspace"}
}

// FilesOrErr returns the Files value or an error if the edge
// was not loaded in eager-loading.
func (e UploadBatchEdges) FilesOrErr() ([]*UploadBatchFile, error) {
	if e.loadedTypes[1] {
		return e.Files, nil
	}
	return nil, &NotLoadedError{edge: "files"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UploadBatch) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case uploadbatch.FieldTotalFiles, uploadbatch.FieldCompletedFiles, uploadbatch.FieldFailedFiles, uploadbatch.FieldTotalBytes, uploadbatch.FieldTransferredBytes:
			values[i] = new(sql.NullInt64)
		case uploadbatch.FieldParentRemoteID, uploadbatch.FieldStatus:
			values[i] = new(sql.NullString)
		case uploadbatch.FieldCreatedAt, uploadbatch.FieldCompletedAt:
			values[i] = new(sql.NullTime)
		case uploadbatch.FieldID, uploadbatch.FieldWorkspaceID, uploadbatch.FieldProviderID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UploadBatch fields.
func (_m *UploadBatch) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case uploadbatch.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case uploadbatch.FieldWorkspaceID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field workspace_id", values[i])
			} else if value != nil {
				_m.WorkspaceID = *value
			}
		case uploadbatch.FieldProviderID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field provider_id", values[i])
			} else if value != nil {
				_m.ProviderID = *value
			}
		case uploadbatch.FieldParentRemoteID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field parent_remote_id", values[i])
			} else if value.Valid {
				_m.ParentRemoteID = value.String
			}
		case uploadbatch.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case uploadbatch.FieldTotalFiles:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_files", values[i])
			} else if value.Valid {
				_m.TotalFiles = int(value.Int64)
			}
		case uploadbatch.FieldCompletedFiles:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field completed_files", values[i])
			} else if value.Valid {
				_m.CompletedFiles = int(value.Int64)
			}
		case uploadbatch.FieldFailedFiles:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field failed_files", values[i])
			} else if value.Valid {
				_m.FailedFiles = int(value.Int64)
			}
		case uploadbatch.FieldTotalBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_bytes", values[i])
			} else if value.Valid {
				_m.TotalBytes = value.Int64
			}
		case uploadbatch.FieldTransferredBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field transferred_bytes", values[i])
			} else if value.Valid {
				_m.TransferredBytes = value.Int64
			}
		case uploadbatch.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case uploadbatch.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				_m.CompletedAt = new(time.Time)
				*_m.CompletedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UploadBatch.
// This includes values selected through modifiers, order, etc.
func (_m *UploadBatch) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryWorkspace queries the "workspace" edge of the UploadBatch entity.
func (_m *UploadBatch) QueryWorkspace() *WorkspaceQuery {
	return NewUploadBatchClient(_m.config).QueryWorkspace(_m)
}

// QueryFiles queries the "files" edge of the UploadBatch entity.
func (_m *UploadBatch) QueryFiles() *UploadBatchFileQuery {
	return NewUploadBatchClient(_m.config).QueryFiles(_m)
}

// Update returns a builder for updating this UploadBatch.
// Note that you need to call UploadBatch.Unwrap() before calling this method if this UploadBatch
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UploadBatch) Update() *UploadBatchUpdateOne {
	return NewUploadBatchClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UploadBatch entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UploadBatch) Unwrap() *UploadBatch {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UploadBatch is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UploadBatch) String() string {
	var builder strings.Builder
	builder.WriteString("UploadBatch(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("workspace_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.WorkspaceID))
	builder.WriteString(", ")
	builder.WriteString("provider_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProviderID))
	builder.WriteString(", ")
	builder.WriteString("parent_remote_id=")
	builder.WriteString(_m.ParentRemoteID)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("total_files=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalFiles))
	builder.WriteString(", ")
	builder.WriteString("completed_files=")
	builder.WriteString(fmt.Sprintf("%v", _m.CompletedFiles))
	builder.WriteString(", ")
	builder.WriteString("failed_files=")
	builder.WriteString(fmt.Sprintf("%v", _m.FailedFiles))
	builder.WriteString(", ")
	builder.WriteString("total_bytes=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalBytes))
	builder.WriteString(", ")
	builder.WriteString("transferred_bytes=")
	builder.WriteString(fmt.Sprintf("%v", _m.TransferredBytes))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.CompletedAt; v != nil {
		builder.WriteString("completed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// UploadBatches is a parsable slice of UploadBatch.
type UploadBatches []*UploadBatch
