// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/drivebase/drivebase/internal/ent/predicate"
	"github.com/drivebase/drivebase/internal/ent/role"
	"github.com/drivebase/drivebase/internal/ent/user"
	"github.com/drivebase/drivebase/internal/ent/workspace"
	"github.com/drivebase/drivebase/internal/ent/workspacemember"
	"github.com/google/uuid"
)

// WorkspaceMemberUpdate is the builder for updating WorkspaceMember entities.
type WorkspaceMemberUpdate struct {
	config
	hooks    []Hook
	mutation *WorkspaceMemberMutation
}

// Where appends a list predicates to the WorkspaceMemberUpdate builder.
func (_u *WorkspaceMemberUpdate) Where(ps ...predicate.WorkspaceMember) *WorkspaceMemberUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *WorkspaceMemberUpdate) SetUserID(v uuid.UUID) *WorkspaceMemberUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *WorkspaceMemberUpdate) SetNillableUserID(v *uuid.UUID) *WorkspaceMemberUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetWorkspaceID sets the "workspace_id" field.
func (_u *WorkspaceMemberUpdate) SetWorkspaceID(v uuid.UUID) *WorkspaceMemberUpdate {
	_u.mutation.SetWorkspaceID(v)
	return _u
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (_u *WorkspaceMemberUpdate) SetNillableWorkspaceID(v *uuid.UUID) *WorkspaceMemberUpdate {
	if v != nil {
		_u.SetWorkspaceID(*v)
	}
	return _u
}

// SetRoleID sets the "role_id" field.
func (_u *WorkspaceMemberUpdate) SetRoleID(v uuid.UUID) *WorkspaceMemberUpdate {
	_u.mutation.SetRoleID(v)
	return _u
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (_u *WorkspaceMemberUpdate) SetNillableRoleID(v *uuid.UUID) *WorkspaceMemberUpdate {
	if v != nil {
		_u.SetRoleID(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *WorkspaceMemberUpdate) SetUser(v *User) *WorkspaceMemberUpdate {
	return _u.SetUserID(v.ID)
}

// SetWorkspace sets the "workspace" edge to the Workspace entity.
func (_u *WorkspaceMemberUpdate) SetWorkspace(v *Workspace) *WorkspaceMemberUpdate {
	return _u.SetWorkspaceID(v.ID)
}

// SetRole sets the "role" edge to the Role entity.
func (_u *WorkspaceMemberUpdate) SetRole(v *Role) *WorkspaceMemberUpdate {
	return _u.SetRoleID(v.ID)
}

// Mutation returns the WorkspaceMemberMutation object of the builder.
func (_u *WorkspaceMemberUpdate) Mutation() *WorkspaceMemberMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *WorkspaceMemberUpdate) ClearUser() *WorkspaceMemberUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearWorkspace clears the "workspace" edge to the Workspace entity.
func (_u *WorkspaceMemberUpdate) ClearWorkspace() *WorkspaceMemberUpdate {
	_u.mutation.ClearWorkspace()
	return _u
}

// ClearRole clears the "role" edge to the Role entity.
func (_u *WorkspaceMemberUpdate) ClearRole() *WorkspaceMemberUpdate {
	_u.mutation.ClearRole()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WorkspaceMemberUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkspaceMemberUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WorkspaceMemberUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkspaceMemberUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WorkspaceMemberUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WorkspaceMember.user"`)
	}
	if _u.mutation.WorkspaceCleared() && len(_u.mutation.WorkspaceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WorkspaceMember.workspace"`)
	}
	if _u.mutation.RoleCleared() && len(_u.mutation.RoleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WorkspaceMember.role"`)
	}
	return nil
}

func (_u *WorkspaceMemberUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(workspacemember.Table, workspacemember.Columns, sqlgraph.NewFieldSpec(workspacemember.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workspacemember.UserTable,
			Columns: []string{workspacemember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workspacemember.UserTable,
			Columns: []string{workspacemember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.WorkspaceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workspacemember.WorkspaceTable,
			Columns: []string{workspacemember.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WorkspaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workspacemember.WorkspaceTable,
			Columns: []string{workspacemember.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workspacemember.RoleTable,
			Columns: []string{workspacemember.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workspacemember.RoleTable,
			Columns: []string{workspacemember.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workspacemember.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WorkspaceMemberUpdateOne is the builder for updating a single WorkspaceMember entity.
type WorkspaceMemberUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WorkspaceMemberMutation
}

// SetUserID sets the "user_id" field.
func (_u *WorkspaceMemberUpdateOne) SetUserID(v uuid.UUID) *WorkspaceMemberUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *WorkspaceMemberUpdateOne) SetNillableUserID(v *uuid.UUID) *WorkspaceMemberUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetWorkspaceID sets the "workspace_id" field.
func (_u *WorkspaceMemberUpdateOne) SetWorkspaceID(v uuid.UUID) *WorkspaceMemberUpdateOne {
	_u.mutation.SetWorkspaceID(v)
	return _u
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (_u *WorkspaceMemberUpdateOne) SetNillableWorkspaceID(v *uuid.UUID) *WorkspaceMemberUpdateOne {
	if v != nil {
		_u.SetWorkspaceID(*v)
	}
	return _u
}

// SetRoleID sets the "role_id" field.
func (_u *WorkspaceMemberUpdateOne) SetRoleID(v uuid.UUID) *WorkspaceMemberUpdateOne {
	_u.mutation.SetRoleID(v)
	return _u
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (_u *WorkspaceMemberUpdateOne) SetNillableRoleID(v *uuid.UUID) *WorkspaceMemberUpdateOne {
	if v != nil {
		_u.SetRoleID(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *WorkspaceMemberUpdateOne) SetUser(v *User) *WorkspaceMemberUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetWorkspace sets the "workspace" edge to the Workspace entity.
func (_u *WorkspaceMemberUpdateOne) SetWorkspace(v *Workspace) *WorkspaceMemberUpdateOne {
	return _u.SetWorkspaceID(v.ID)
}

// SetRole sets the "role" edge to the Role entity.
func (_u *WorkspaceMemberUpdateOne) SetRole(v *Role) *WorkspaceMemberUpdateOne {
	return _u.SetRoleID(v.ID)
}

// Mutation returns the WorkspaceMemberMutation object of the builder.
func (_u *WorkspaceMemberUpdateOne) Mutation() *WorkspaceMemberMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *WorkspaceMemberUpdateOne) ClearUser() *WorkspaceMemberUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearWorkspace clears the "workspace" edge to the Workspace entity.
func (_u *WorkspaceMemberUpdateOne) ClearWorkspace() *WorkspaceMemberUpdateOne {
	_u.mutation.ClearWorkspace()
	return _u
}

// ClearRole clears the "role" edge to the Role entity.
func (_u *WorkspaceMemberUpdateOne) ClearRole() *WorkspaceMemberUpdateOne {
	_u.mutation.ClearRole()
	return _u
}

// Where appends a list predicates to the WorkspaceMemberUpdate builder.
func (_u *WorkspaceMemberUpdateOne) Where(ps ...predicate.WorkspaceMember) *WorkspaceMemberUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WorkspaceMemberUpdateOne) Select(field string, fields ...string) *WorkspaceMemberUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated WorkspaceMember entity.
func (_u *WorkspaceMemberUpdateOne) Save(ctx context.Context) (*WorkspaceMember, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkspaceMemberUpdateOne) SaveX(ctx context.Context) *WorkspaceMember {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WorkspaceMemberUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkspaceMemberUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WorkspaceMemberUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WorkspaceMember.user"`)
	}
	if _u.mutation.WorkspaceCleared() && len(_u.mutation.WorkspaceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WorkspaceMember.workspace"`)
	}
	if _u.mutation.RoleCleared() && len(_u.mutation.RoleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WorkspaceMember.role"`)
	}
	return nil
}

func (_u *WorkspaceMemberUpdateOne) sqlSave(ctx context.Context) (_node *WorkspaceMember, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(workspacemember.Table, workspacemember.Columns, sqlgraph.NewFieldSpec(workspacemember.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WorkspaceMember.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, workspacemember.FieldID)
		for _, f := range fields {
			if !workspacemember.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != workspacemember.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workspacemember.UserTable,
			Columns: []string{workspacemember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workspacemember.UserTable,
			Columns: []string{workspacemember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.WorkspaceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workspacemember.WorkspaceTable,
			Columns: []string{workspacemember.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WorkspaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workspacemember.WorkspaceTable,
			Columns: []string{workspacemember.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workspacemember.RoleTable,
			Columns: []string{workspacemember.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workspacemember.RoleTable,
			Columns: []string{workspacemember.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &WorkspaceMember{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workspacemember.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
