// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// BandwidthLog is the predicate function for bandwidthlog builders.
type BandwidthLog func(*sql.Selector)

// CacheConfig is the predicate function for cacheconfig builders.
type CacheConfig func(*sql.Selector)

// FileNode is the predicate function for filenode builders.
type FileNode func(*sql.Selector)

// Permission is the predicate function for permission builders.
type Permission func(*sql.Selector)

// Provider is the predicate function for provider builders.
type Provider func(*sql.Selector)

// ProviderCredential is the predicate function for providercredential builders.
type ProviderCredential func(*sql.Selector)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)

// Session is the predicate function for session builders.
type Session func(*sql.Selector)

// SharedLink is the predicate function for sharedlink builders.
type SharedLink func(*sql.Selector)

// TransferJob is the predicate function for transferjob builders.
type TransferJob func(*sql.Selector)

// TransferJobFile is the predicate function for transferjobfile builders.
type TransferJobFile func(*sql.Selector)

// UploadBatch is the predicate function for uploadbatch builders.
type UploadBatch func(*sql.Selector)

// UploadBatchFile is the predicate function for uploadbatchfile builders.
type UploadBatchFile func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// Workspace is the predicate function for workspace builders.
type Workspace func(*sql.Selector)

// WorkspaceMember is the predicate function for workspacemember builders.
type WorkspaceMember func(*sql.Selector)
