// Code generated by ent, DO NOT EDIT.

package providercredential

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/drivebase/drivebase/internal/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ProviderCredential {
	return predicate.ProviderCredential(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ProviderCredential {
	return predicate.ProviderCredential(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ProviderCredential {
	return predicate.ProviderCredential(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ProviderCredential {
	return predicate.ProviderCredential(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ProviderCredential {
	return predicate.ProviderCredential(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ProviderCredential {
	return predicate.ProviderCredential(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ProviderCredential {
	return predicate.ProviderCredential(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ProviderCredential {
	return predicate.ProviderCredential(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ProviderCredential {
	return predicate.ProviderCredential(sql.FieldLTE(FieldID, id))
}

// ProviderID applies equality check predicate on the "provider_id" field. It's identical to ProviderIDEQ.
func ProviderID(v uuid.UUID) predicate.ProviderCredential {
	return predicate.ProviderCredential(sql.FieldEQ(FieldProviderID, v))
}

// EncryptedData applies equality check predicate on the "encrypted_data" field. It's identical to EncryptedDataEQ.
func EncryptedData(v []byte) predicate.ProviderCredential {
	return predicate.ProviderCredential(sql.FieldEQ(FieldEncryptedData, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ProviderCredential {
	return predicate.ProviderCredential(sql.FieldEQ(FieldUpdatedAt, v))
}

// ProviderIDEQ applies the EQ predicate on the "provider_id" field.
func ProviderIDEQ(v uuid.UUID) predicate.ProviderCredential {
	return predicate.ProviderCredential(sql.FieldEQ(FieldProviderID, v))
}

// ProviderIDNEQ applies the NEQ predicate on the "provider_id" field.
func ProviderIDNEQ(v uuid.UUID) predicate.ProviderCredential {
	return predicate.ProviderCredential(sql.FieldNEQ(FieldProviderID, v))
}

// ProviderIDIn applies the In predicate on the "provider_id" field.
func ProviderIDIn(vs ...uuid.UUID) predicate.ProviderCredential {
	return predicate.ProviderCredential(sql.FieldIn(FieldProviderID, vs...))
}

// ProviderIDNotIn applies the NotIn predicate on the "provider_id" field.
func ProviderIDNotIn(vs ...uuid.UUID) predicate.ProviderCredential {
	return predicate.ProviderCredential(sql.FieldNotIn(FieldProviderID, vs...))
}

// EncryptedDataEQ applies the EQ predicate on the "encrypted_data" field.
func EncryptedDataEQ(v []byte) predicate.ProviderCredential {
	return predicate.ProviderCredential(sql.FieldEQ(FieldEncryptedData, v))
}

// EncryptedDataNEQ applies the NEQ predicate on the "encrypted_data" field.
func EncryptedDataNEQ(v []byte) predicate.ProviderCredential {
	return predicate.ProviderCredential(sql.FieldNEQ(FieldEncryptedData, v))
}

// EncryptedDataIn applies the In predicate on the "encrypted_data" field.
func EncryptedDataIn(vs ...[]byte) predicate.ProviderCredential {
	return predicate.ProviderCredential(sql.FieldIn(FieldEncryptedData, vs...))
}

// EncryptedDataNotIn applies the NotIn predicate on the "encrypted_data" field.
func EncryptedDataNotIn(vs ...[]byte) predicate.ProviderCredential {
	return predicate.ProviderCredential(sql.FieldNotIn(FieldEncryptedData, vs...))
}

// EncryptedDataGT applies the GT predicate on the "encrypted_data" field.
func EncryptedDataGT(v []byte) predicate.ProviderCredential {
	return predicate.ProviderCredential(sql.FieldGT(FieldEncryptedData, v))
}

// EncryptedDataGTE applies the GTE predicate on the "encrypted_data" field.
func EncryptedDataGTE(v []byte) predicate.ProviderCredential {
	return predicate.ProviderCredential(sql.FieldGTE(FieldEncryptedData, v))
}

// EncryptedDataLT applies the LT predicate on the "encrypted_data" field.
func EncryptedDataLT(v []byte) predicate.ProviderCredential {
	return predicate.ProviderCredential(sql.FieldLT(FieldEncryptedData, v))
}

// EncryptedDataLTE applies the LTE predicate on the "encrypted_data" field.
func EncryptedDataLTE(v []byte) predicate.ProviderCredential {
	return predicate.ProviderCredential(sql.FieldLTE(FieldEncryptedData, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ProviderCredential {
	return predicate.ProviderCredential(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ProviderCredential {
	return predicate.ProviderCredential(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ProviderCredential {
	return predicate.ProviderCredential(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ProviderCredential {
	return predicate.ProviderCredential(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ProviderCredential {
	return predicate.ProviderCredential(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ProviderCredential {
	return predicate.ProviderCredential(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ProviderCredential {
	return predicate.ProviderCredential(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ProviderCredential {
	return predicate.ProviderCredential(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasProvider applies the HasEdge predicate on the "provider" edge.
func HasProvider() predicate.ProviderCredential {
	return predicate.ProviderCredential(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, ProviderTable, ProviderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProviderWith applies the HasEdge predicate on the "provider" edge with a given conditions (other predicates).
func HasProviderWith(preds ...predicate.Provider) predicate.ProviderCredential {
	return predicate.ProviderCredential(func(s *sql.Selector) {
		step := newProviderStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProviderCredential) predicate.ProviderCredential {
	return predicate.ProviderCredential(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProviderCredential) predicate.ProviderCredential {
	return predicate.ProviderCredential(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProviderCredential) predicate.ProviderCredential {
	return predicate.ProviderCredential(sql.NotPredicates(p))
}
