// Code generated by ent, DO NOT EDIT.

package workspace

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the workspace type in the database.
	Label = "workspace"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldSlug holds the string denoting the slug field in the database.
	FieldSlug = "slug"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeMembers holds the string denoting the members edge name in mutations.
	EdgeMembers = "members"
	// EdgeProviders holds the string denoting the providers edge name in mutations.
	EdgeProviders = "providers"
	// EdgeRoles holds the string denoting the roles edge name in mutations.
	EdgeRoles = "roles"
	// EdgeUploadBatches holds the string denoting the upload_batches edge name in mutations.
	EdgeUploadBatches = "upload_batches"
	// EdgeTransferJobs holds the string denoting the transfer_jobs edge name in mutations.
	EdgeTransferJobs = "transfer_jobs"
	// EdgeSharedLinks holds the string denoting the shared_links edge name in mutations.
	EdgeSharedLinks = "shared_links"
	// EdgeBandwidthLogs holds the string denoting the bandwidth_logs edge name in mutations.
	EdgeBandwidthLogs = "bandwidth_logs"
	// EdgeOauthApps holds the string denoting the oauth_apps edge name in mutations.
	EdgeOauthApps = "oauth_apps"
	// Table holds the table name of the workspace in the database.
	Table = "workspaces"
	// MembersTable is the table that holds the members relation/edge.
	MembersTable = "workspace_members"
	// MembersInverseTable is the table name for the WorkspaceMember entity.
	// It exists in this package in order to avoid circular dependency with the "workspacemember" package.
	MembersInverseTable = "workspace_members"
	// MembersColumn is the table column denoting the members relation/edge.
	MembersColumn = "workspace_id"
	// ProvidersTable is the table that holds the providers relation/edge.
	ProvidersTable = "providers"
	// ProvidersInverseTable is the table name for the Provider entity.
	// It exists in this package in order to avoid circular dependency with the "provider" package.
	ProvidersInverseTable = "providers"
	// ProvidersColumn is the table column denoting the providers relation/edge.
	ProvidersColumn = "workspace_id"
	// RolesTable is the table that holds the roles relation/edge.
	RolesTable = "roles"
	// RolesInverseTable is the table name for the Role entity.
	// It exists in this package in order to avoid circular dependency with the "role" package.
	RolesInverseTable = "roles"
	// RolesColumn is the table column denoting the roles relation/edge.
	RolesColumn = "workspace_id"
	// UploadBatchesTable is the table that holds the upload_batches relation/edge.
	UploadBatchesTable = "upload_batches"
	// UploadBatchesInverseTable is the table name for the UploadBatch entity.
	// It exists in this package in order to avoid circular dependency with the "uploadbatch" package.
	UploadBatchesInverseTable = "upload_batches"
	// UploadBatchesColumn is the table column denoting the upload_batches relation/edge.
	UploadBatchesColumn = "workspace_id"
	// TransferJobsTable is the table that holds the transfer_jobs relation/edge.
	TransferJobsTable = "transfer_jobs"
	// TransferJobsInverseTable is the table name for the TransferJob entity.
	// It exists in this package in order to avoid circular dependency with the "transferjob" package.
	TransferJobsInverseTable = "transfer_jobs"
	// TransferJobsColumn is the table column denoting the transfer_jobs relation/edge.
	TransferJobsColumn = "workspace_id"
	// SharedLinksTable is the table that holds the shared_links relation/edge.
	SharedLinksTable = "shared_links"
	// SharedLinksInverseTable is the table name for the SharedLink entity.
	// It exists in this package in order to avoid circular dependency with the "sharedlink" package.
	SharedLinksInverseTable = "shared_links"
	// SharedLinksColumn is the table column denoting the shared_links relation/edge.
	SharedLinksColumn = "workspace_id"
	// BandwidthLogsTable is the table that holds the bandwidth_logs relation/edge.
	BandwidthLogsTable = "bandwidth_logs"
	// BandwidthLogsInverseTable is the table name for the BandwidthLog entity.
	// It exists in this package in order to avoid circular dependency with the "bandwidthlog" package.
	BandwidthLogsInverseTable = "bandwidth_logs"
	// BandwidthLogsColumn is the table column denoting the bandwidth_logs relation/edge.
	BandwidthLogsColumn = "workspace_id"
	// OauthAppsTable is the table that holds the oauth_apps relation/edge.
	OauthAppsTable = "oauth_apps"
	// OauthAppsInverseTable is the table name for the OAuthApp entity.
	// It exists in this package in order to avoid circular dependency with the "oauthapp" package.
	OauthAppsInverseTable = "oauth_apps"
	// OauthAppsColumn is the table column denoting the oauth_apps relation/edge.
	OauthAppsColumn = "workspace_id"
)

// Columns holds all SQL columns for workspace fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldSlug,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	SlugValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Workspace queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// BySlug orders the results by the slug field.
func BySlug(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSlug, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByMembersCount orders the results by members count.
func ByMembersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newMembersStep(), opts...)
	}
}

// ByMembers orders the results by members terms.
func ByMembers(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMembersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByProvidersCount orders the results by providers count.
func ByProvidersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newProvidersStep(), opts...)
	}
}

// ByProviders orders the results by providers terms.
func ByProviders(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProvidersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByRolesCount orders the results by roles count.
func ByRolesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRolesStep(), opts...)
	}
}

// ByRoles orders the results by roles terms.
func ByRoles(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRolesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByUploadBatchesCount orders the results by upload_batches count.
func ByUploadBatchesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newUploadBatchesStep(), opts...)
	}
}

// ByUploadBatches orders the results by upload_batches terms.
func ByUploadBatches(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUploadBatchesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByTransferJobsCount orders the results by transfer_jobs count.
func ByTransferJobsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTransferJobsStep(), opts...)
	}
}

// ByTransferJobs orders the results by transfer_jobs terms.
func ByTransferJobs(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTransferJobsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// BySharedLinksCount orders the results by shared_links count.
func BySharedLinksCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSharedLinksStep(), opts...)
	}
}

// BySharedLinks orders the results by shared_links terms.
func BySharedLinks(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSharedLinksStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByBandwidthLogsCount orders the results by bandwidth_logs count.
func ByBandwidthLogsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newBandwidthLogsStep(), opts...)
	}
}

// ByBandwidthLogs orders the results by bandwidth_logs terms.
func ByBandwidthLogs(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBandwidthLogsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByOauthAppsCount orders the results by oauth_apps count.
func ByOauthAppsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newOauthAppsStep(), opts...)
	}
}

// ByOauthApps orders the results by oauth_apps terms.
func ByOauthApps(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOauthAppsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newMembersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MembersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, MembersTable, MembersColumn),
	)
}
func newProvidersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProvidersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ProvidersTable, ProvidersColumn),
	)
}
func newRolesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RolesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, RolesTable, RolesColumn),
	)
}
func newUploadBatchesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UploadBatchesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, UploadBatchesTable, UploadBatchesColumn),
	)
}
func newTransferJobsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TransferJobsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TransferJobsTable, TransferJobsColumn),
	)
}
func newSharedLinksStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SharedLinksInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SharedLinksTable, SharedLinksColumn),
	)
}
func newBandwidthLogsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BandwidthLogsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, BandwidthLogsTable, BandwidthLogsColumn),
	)
}
func newOauthAppsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OauthAppsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, OauthAppsTable, OauthAppsColumn),
	)
}
