package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"

	"github.com/drivebase/drivebase/internal/graph"
)

// AvailableProviders is the resolver for the availableProviders field.
func (r *queryResolver) AvailableProviders(ctx context.Context) ([]*graph.AvailableProvider, error) {
	return availableProviders, nil
}
