package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"
	"time"

	"github.com/drivebase/drivebase/internal/auth"
	"github.com/drivebase/drivebase/internal/crypto"
	entoauthapp "github.com/drivebase/drivebase/internal/ent/oauthapp"
	entschema "github.com/drivebase/drivebase/internal/ent/schema"
	"github.com/drivebase/drivebase/internal/graph"
	"github.com/drivebase/drivebase/internal/storage"
	"golang.org/x/oauth2"
	"golang.org/x/oauth2/google"
	googledrive "google.golang.org/api/drive/v3"
)

// SaveOAuthApp is the resolver for the saveOAuthApp field.
func (r *mutationResolver) SaveOAuthApp(ctx context.Context, input graph.SaveOAuthAppInput) (*graph.OAuthApp, error) {
	workspaceID, ok := auth.WorkspaceIDFromCtx(ctx)
	if !ok {
		return nil, auth.ErrUnauthenticated
	}
	if err := auth.Check(ctx, r.DB, string(entschema.ResourceTypeWorkspace), workspaceID, string(entschema.ActionWrite)); err != nil {
		return nil, err
	}

	encrypted, err := crypto.Encrypt([]byte(input.ClientSecret), r.Config.Crypto.EncryptionKey)
	if err != nil {
		return nil, fmt.Errorf("internal error encrypting client secret")
	}

	provType := string(input.ProviderType)

	// Upsert: update if exists, create if not
	existing, err := r.DB.OAuthApp.Query().
		Where(entoauthapp.WorkspaceID(workspaceID), entoauthapp.ProviderType(provType)).
		Only(ctx)
	if err == nil {
		// Update
		q := r.DB.OAuthApp.UpdateOneID(existing.ID).
			SetClientID(input.ClientID).
			SetEncryptedClientSecret(encrypted)
		if input.Alias != nil {
			q = q.SetAlias(*input.Alias)
		} else {
			q = q.ClearAlias()
		}
		updated, err := q.Save(ctx)
		if err != nil {
			return nil, fmt.Errorf("internal error")
		}
		return mapOAuthApp(updated), nil
	}

	// Create
	q := r.DB.OAuthApp.Create().
		SetWorkspaceID(workspaceID).
		SetProviderType(provType).
		SetClientID(input.ClientID).
		SetEncryptedClientSecret(encrypted)
	if input.Alias != nil {
		q = q.SetAlias(*input.Alias)
	}
	app, err := q.Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("internal error")
	}
	return mapOAuthApp(app), nil
}

// DeleteOAuthApp is the resolver for the deleteOAuthApp field.
func (r *mutationResolver) DeleteOAuthApp(ctx context.Context, providerType graph.ProviderType) (bool, error) {
	workspaceID, ok := auth.WorkspaceIDFromCtx(ctx)
	if !ok {
		return false, auth.ErrUnauthenticated
	}
	if err := auth.Check(ctx, r.DB, string(entschema.ResourceTypeWorkspace), workspaceID, string(entschema.ActionAdmin)); err != nil {
		return false, err
	}

	_, err := r.DB.OAuthApp.Delete().
		Where(entoauthapp.WorkspaceID(workspaceID), entoauthapp.ProviderType(string(providerType))).
		Exec(ctx)
	if err != nil {
		return false, fmt.Errorf("internal error")
	}
	return true, nil
}

// InitiateOAuth is the resolver for the initiateOAuth field.
func (r *mutationResolver) InitiateOAuth(ctx context.Context, providerType graph.ProviderType, providerName string) (string, error) {
	workspaceID, ok := auth.WorkspaceIDFromCtx(ctx)
	if !ok {
		return "", auth.ErrUnauthenticated
	}
	if err := auth.Check(ctx, r.DB, string(entschema.ResourceTypeWorkspace), workspaceID, string(entschema.ActionWrite)); err != nil {
		return "", err
	}

	app, err := r.DB.OAuthApp.Query().
		Where(entoauthapp.WorkspaceID(workspaceID), entoauthapp.ProviderType(string(providerType))).
		Only(ctx)
	if err != nil {
		return "", fmt.Errorf("no OAuth app configured for %s — call saveOAuthApp first", providerType)
	}

	clientSecret, err := crypto.Decrypt(app.EncryptedClientSecret, r.Config.Crypto.EncryptionKey)
	if err != nil {
		return "", fmt.Errorf("internal error decrypting client secret")
	}

	oauthCfg := oauthConfigForType(storage.ProviderType(providerType), app.ClientID, string(clientSecret), r.Config.Server.OAuthCallbackURL)
	if oauthCfg == nil {
		return "", fmt.Errorf("provider type %s does not support OAuth", providerType)
	}

	// Store state for CSRF protection and to recover context in callback
	state, err := r.DB.OAuthState.Create().
		SetWorkspaceID(workspaceID).
		SetOauthAppID(app.ID).
		SetProviderType(string(providerType)).
		SetProviderName(providerName).
		SetExpiresAt(time.Now().Add(10 * time.Minute)).
		Save(ctx)
	if err != nil {
		return "", fmt.Errorf("internal error creating OAuth state")
	}

	authURL := oauthCfg.AuthCodeURL(state.ID.String(), oauth2.AccessTypeOffline, oauth2.ApprovalForce)
	return authURL, nil
}

// OauthApp is the resolver for the oauthApp field.
func (r *queryResolver) OauthApp(ctx context.Context, providerType graph.ProviderType) (*graph.OAuthApp, error) {
	workspaceID, ok := auth.WorkspaceIDFromCtx(ctx)
	if !ok {
		return nil, auth.ErrUnauthenticated
	}
	if err := auth.Check(ctx, r.DB, string(entschema.ResourceTypeWorkspace), workspaceID, string(entschema.ActionRead)); err != nil {
		return nil, err
	}

	app, err := r.DB.OAuthApp.Query().
		Where(entoauthapp.WorkspaceID(workspaceID), entoauthapp.ProviderType(string(providerType))).
		Only(ctx)
	if err != nil {
		return nil, nil // not found → null, not an error
	}
	return mapOAuthApp(app), nil
}

// OauthApps is the resolver for the oauthApps field.
func (r *queryResolver) OauthApps(ctx context.Context) ([]*graph.OAuthApp, error) {
	workspaceID, ok := auth.WorkspaceIDFromCtx(ctx)
	if !ok {
		return nil, auth.ErrUnauthenticated
	}
	if err := auth.Check(ctx, r.DB, string(entschema.ResourceTypeWorkspace), workspaceID, string(entschema.ActionRead)); err != nil {
		return nil, err
	}

	apps, err := r.DB.OAuthApp.Query().
		Where(entoauthapp.WorkspaceID(workspaceID)).
		All(ctx)
	if err != nil {
		return nil, fmt.Errorf("internal error")
	}

	out := make([]*graph.OAuthApp, len(apps))
	for i, a := range apps {
		out[i] = mapOAuthApp(a)
	}
	return out, nil
}

// oauthConfigForType returns the oauth2.Config for the given provider type.
func oauthConfigForType(provType storage.ProviderType, clientID, clientSecret, callbackURL string) *oauth2.Config {
	switch provType {
	case storage.ProviderTypeGoogleDrive:
		return &oauth2.Config{
			ClientID:     clientID,
			ClientSecret: clientSecret,
			RedirectURL:  callbackURL,
			Endpoint:     google.Endpoint,
			Scopes:       []string{googledrive.DriveScope},
		}
	default:
		return nil
	}
}
