package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"
	"time"

	"github.com/drivebase/drivebase/internal/auth"
	"github.com/drivebase/drivebase/internal/crypto"
	entoauthapp "github.com/drivebase/drivebase/internal/ent/oauthapp"
	"github.com/drivebase/drivebase/internal/graph"
	"github.com/drivebase/drivebase/internal/storage"
	"github.com/google/uuid"
	"golang.org/x/oauth2"
)

// SaveOAuthApp is the resolver for the saveOAuthApp field.
func (r *mutationResolver) SaveOAuthApp(ctx context.Context, input graph.SaveOAuthAppInput) (*graph.OAuthApp, error) {
	u, err := auth.UserFromCtx(ctx)
	if err != nil {
		return nil, auth.ErrUnauthenticated
	}

	encrypted, err := crypto.Encrypt([]byte(input.ClientSecret), r.Config.Crypto.EncryptionKey)
	if err != nil {
		return nil, fmt.Errorf("internal error encrypting client secret")
	}

	provType := string(input.ProviderType)

	// Upsert: update if exists, create if not
	existing, err := r.DB.OAuthApp.Query().
		Where(entoauthapp.UserID(u.ID), entoauthapp.ProviderType(provType)).
		Only(ctx)
	if err == nil {
		// Update
		q := r.DB.OAuthApp.UpdateOneID(existing.ID).
			SetClientID(input.ClientID).
			SetEncryptedClientSecret(encrypted)
		if input.Alias != nil {
			q = q.SetAlias(*input.Alias)
		} else {
			q = q.ClearAlias()
		}
		updated, err := q.Save(ctx)
		if err != nil {
			return nil, fmt.Errorf("internal error: %w", err)
		}
		return mapOAuthApp(updated), nil
	}

	// Create
	q := r.DB.OAuthApp.Create().
		SetUserID(u.ID).
		SetProviderType(provType).
		SetClientID(input.ClientID).
		SetEncryptedClientSecret(encrypted)
	if input.Alias != nil {
		q = q.SetAlias(*input.Alias)
	}
	app, err := q.Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("internal error: %w", err)
	}
	return mapOAuthApp(app), nil
}

// DeleteOAuthApp is the resolver for the deleteOAuthApp field.
func (r *mutationResolver) DeleteOAuthApp(ctx context.Context, providerType graph.ProviderType) (bool, error) {
	u, err := auth.UserFromCtx(ctx)
	if err != nil {
		return false, auth.ErrUnauthenticated
	}

	_, err = r.DB.OAuthApp.Delete().
		Where(entoauthapp.UserID(u.ID), entoauthapp.ProviderType(string(providerType))).
		Exec(ctx)
	if err != nil {
		return false, fmt.Errorf("internal error: %w", err)
	}
	return true, nil
}

// InitiateOAuth is the resolver for the initiateOAuth field.
func (r *mutationResolver) InitiateOAuth(ctx context.Context, oauthAppID uuid.UUID, providerName string) (string, error) {
	u, err := auth.UserFromCtx(ctx)
	if err != nil {
		return "", auth.ErrUnauthenticated
	}

	app, err := r.DB.OAuthApp.Query().
		Where(entoauthapp.UserID(u.ID), entoauthapp.ID(oauthAppID)).
		Only(ctx)
	if err != nil {
		return "", fmt.Errorf("OAuth app not found")
	}

	clientSecret, err := crypto.Decrypt(app.EncryptedClientSecret, r.Config.Crypto.EncryptionKey)
	if err != nil {
		return "", fmt.Errorf("internal error decrypting client secret")
	}

	oauthCfg := oauthConfigForType(storage.ProviderType(app.ProviderType), app.ClientID, string(clientSecret), r.Config.Server.OAuthCallbackURL)
	if oauthCfg == nil {
		return "", fmt.Errorf("provider type %s does not support OAuth", app.ProviderType)
	}

	// Store state for CSRF protection and to recover context in callback
	state, err := r.DB.OAuthState.Create().
		SetUserID(u.ID).
		SetOauthAppID(app.ID).
		SetProviderType(app.ProviderType).
		SetProviderName(providerName).
		SetExpiresAt(time.Now().Add(10 * time.Minute)).
		Save(ctx)
	if err != nil {
		return "", fmt.Errorf("internal error creating OAuth state")
	}

	authURL := oauthCfg.AuthCodeURL(state.ID.String(), oauth2.AccessTypeOffline, oauth2.ApprovalForce)
	return authURL, nil
}

// OauthApp is the resolver for the oauthApp field.
func (r *queryResolver) OauthApp(ctx context.Context, providerType graph.ProviderType) (*graph.OAuthApp, error) {
	u, err := auth.UserFromCtx(ctx)
	if err != nil {
		return nil, auth.ErrUnauthenticated
	}

	app, err := r.DB.OAuthApp.Query().
		Where(entoauthapp.UserID(u.ID), entoauthapp.ProviderType(string(providerType))).
		Only(ctx)
	if err != nil {
		return nil, nil // not found → null, not an error
	}
	return mapOAuthApp(app), nil
}

// OauthApps is the resolver for the oauthApps field.
func (r *queryResolver) OauthApps(ctx context.Context) ([]*graph.OAuthApp, error) {
	u, err := auth.UserFromCtx(ctx)
	if err != nil {
		return nil, auth.ErrUnauthenticated
	}

	apps, err := r.DB.OAuthApp.Query().
		Where(entoauthapp.UserID(u.ID)).
		All(ctx)
	if err != nil {
		return nil, fmt.Errorf("internal error: %w", err)
	}

	out := make([]*graph.OAuthApp, len(apps))
	for i, a := range apps {
		out[i] = mapOAuthApp(a)
	}
	return out, nil
}
