package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"

	"github.com/drivebase/drivebase/internal/auth"
	"github.com/drivebase/drivebase/internal/crypto"
	"github.com/drivebase/drivebase/internal/ent"
	entprovider "github.com/drivebase/drivebase/internal/ent/provider"
	entproviderquota "github.com/drivebase/drivebase/internal/ent/providerquota"
	entschema "github.com/drivebase/drivebase/internal/ent/schema"
	"github.com/drivebase/drivebase/internal/graph"
	"github.com/drivebase/drivebase/internal/storage"
	_ "github.com/drivebase/drivebase/internal/storage/googledrive"
	"github.com/google/uuid"
)

// ConnectProvider is the resolver for the connectProvider field.
func (r *mutationResolver) ConnectProvider(ctx context.Context, input graph.ConnectProviderInput) (*graph.Provider, error) {
	u, err := auth.UserFromCtx(ctx)
	if err != nil {
		return nil, auth.ErrUnauthenticated
	}

	providerType := storage.ProviderType(input.Type)
	rawCreds := storage.Credentials(input.Credentials)

	// Validate credentials by instantiating the provider and calling Validate()
	prov, err := storage.New(providerType, rawCreds)
	if err != nil {
		return nil, fmt.Errorf("invalid credentials: %w", err)
	}
	if err := prov.Validate(ctx); err != nil {
		return nil, fmt.Errorf("provider validation failed: %w", err)
	}

	// Encrypt credentials before persisting
	encrypted, err := crypto.Encrypt(rawCreds, r.Config.Crypto.EncryptionKey)
	if err != nil {
		return nil, fmt.Errorf("internal error encrypting credentials")
	}

	authType := authTypeForProvider(providerType)

	var gp *graph.Provider
	if err := withTx(ctx, r.DB, func(tx *ent.Tx) error {
		p, err := tx.Provider.Create().
			SetUserID(u.ID).
			SetType(string(providerType)).
			SetName(input.Name).
			SetAuthType(string(authType)).
			Save(ctx)
		if err != nil {
			return fmt.Errorf("internal error creating provider")
		}

		_, err = tx.ProviderCredential.Create().
			SetProviderID(p.ID).
			SetEncryptedData(encrypted).
			Save(ctx)
		if err != nil {
			return fmt.Errorf("internal error storing credentials")
		}

		// Default cache config
		_, err = tx.CacheConfig.Create().
			SetProviderID(p.ID).
			SetEnabled(true).
			SetTTLSeconds(300).
			Save(ctx)
		if err != nil {
			return fmt.Errorf("internal error creating cache config")
		}

		gp = mapProvider(p)
		return nil
	}); err != nil {
		return nil, err
	}

	return gp, nil
}

// DisconnectProvider is the resolver for the disconnectProvider field.
func (r *mutationResolver) DisconnectProvider(ctx context.Context, id uuid.UUID) (bool, error) {
	u, err := auth.UserFromCtx(ctx)
	if err != nil {
		return false, auth.ErrUnauthenticated
	}

	p, err := r.DB.Provider.Get(ctx, id)
	if err != nil {
		return false, fmt.Errorf("provider not found")
	}
	if p.UserID != u.ID {
		return false, fmt.Errorf("forbidden")
	}

	if err := r.DB.Provider.DeleteOneID(id).Exec(ctx); err != nil {
		return false, fmt.Errorf("internal error: %w", err)
	}
	return true, nil
}

// UpdateProvider is the resolver for the updateProvider field.
func (r *mutationResolver) UpdateProvider(ctx context.Context, id uuid.UUID, input graph.UpdateProviderInput) (*graph.Provider, error) {
	u, err := auth.UserFromCtx(ctx)
	if err != nil {
		return nil, auth.ErrUnauthenticated
	}

	p, err := r.DB.Provider.Get(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("provider not found")
	}
	if p.UserID != u.ID {
		return nil, fmt.Errorf("forbidden")
	}

	q := r.DB.Provider.UpdateOneID(id)
	if input.Name != nil {
		q = q.SetName(*input.Name)
	}
	updated, err := q.Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("internal error: %w", err)
	}
	return mapProvider(updated), nil
}

// ValidateProvider is the resolver for the validateProvider field.
func (r *mutationResolver) ValidateProvider(ctx context.Context, id uuid.UUID) (*graph.ProviderValidationResult, error) {
	u, err := auth.UserFromCtx(ctx)
	if err != nil {
		return nil, auth.ErrUnauthenticated
	}

	p, err := r.DB.Provider.Get(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("provider not found")
	}
	if p.UserID != u.ID {
		return nil, fmt.Errorf("forbidden")
	}

	prov, err := loadProviderByID(ctx, r.DB, r.Config.Crypto.EncryptionKey, id)
	if err != nil {
		errStr := err.Error()
		return &graph.ProviderValidationResult{Ok: false, Error: &errStr}, nil
	}

	if err := prov.Validate(ctx); err != nil {
		errStr := err.Error()
		_ = r.DB.Provider.UpdateOneID(id).SetStatus(string(entschema.ProviderStatusError)).Exec(ctx)
		return &graph.ProviderValidationResult{Ok: false, Error: &errStr}, nil
	}

	_ = r.DB.Provider.UpdateOneID(id).SetStatus(string(entschema.ProviderStatusActive)).Exec(ctx)
	return &graph.ProviderValidationResult{Ok: true}, nil
}

// RefreshProviderQuota is the resolver for the refreshProviderQuota field.
func (r *mutationResolver) RefreshProviderQuota(ctx context.Context, providerID uuid.UUID) (*graph.ProviderQuota, error) {
	u, err := auth.UserFromCtx(ctx)
	if err != nil {
		return nil, auth.ErrUnauthenticated
	}

	p, err := r.DB.Provider.Get(ctx, providerID)
	if err != nil {
		return nil, fmt.Errorf("provider not found")
	}
	if p.UserID != u.ID {
		return nil, fmt.Errorf("forbidden")
	}

	return refreshQuota(ctx, r.Resolver, providerID)
}

// Providers is the resolver for the providers field.
func (r *queryResolver) Providers(ctx context.Context) ([]*graph.Provider, error) {
	u, err := auth.UserFromCtx(ctx)
	if err != nil {
		return nil, auth.ErrUnauthenticated
	}

	providers, err := r.DB.Provider.Query().
		Where(entprovider.UserID(u.ID)).
		WithQuota().
		All(ctx)
	if err != nil {
		return nil, fmt.Errorf("internal error: %w", err)
	}

	out := make([]*graph.Provider, len(providers))
	for i, p := range providers {
		out[i] = mapProvider(p)
	}
	return out, nil
}

// Provider is the resolver for the provider field.
func (r *queryResolver) Provider(ctx context.Context, id uuid.UUID) (*graph.Provider, error) {
	u, err := auth.UserFromCtx(ctx)
	if err != nil {
		return nil, auth.ErrUnauthenticated
	}

	p, err := r.DB.Provider.Query().
		Where(entprovider.ID(id)).
		WithQuota().
		Only(ctx)
	if err != nil {
		return nil, fmt.Errorf("provider not found")
	}
	if p.UserID != u.ID {
		return nil, fmt.Errorf("forbidden")
	}

	return mapProvider(p), nil
}

// ProviderQuota is the resolver for the providerQuota field.
func (r *queryResolver) ProviderQuota(ctx context.Context, providerID uuid.UUID) (*graph.ProviderQuota, error) {
	u, err := auth.UserFromCtx(ctx)
	if err != nil {
		return nil, auth.ErrUnauthenticated
	}

	p, err := r.DB.Provider.Get(ctx, providerID)
	if err != nil {
		return nil, fmt.Errorf("provider not found")
	}
	if p.UserID != u.ID {
		return nil, fmt.Errorf("forbidden")
	}

	q, err := r.DB.ProviderQuota.Query().
		Where(entproviderquota.ProviderID(providerID)).
		Only(ctx)
	if err != nil {
		return nil, nil // no quota record yet
	}
	return mapProviderQuota(q), nil
}
