// Code generated by ent, DO NOT EDIT.

package cacheconfig

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/drivebase/drivebase/internal/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.CacheConfig {
	return predicate.CacheConfig(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.CacheConfig {
	return predicate.CacheConfig(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.CacheConfig {
	return predicate.CacheConfig(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.CacheConfig {
	return predicate.CacheConfig(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.CacheConfig {
	return predicate.CacheConfig(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.CacheConfig {
	return predicate.CacheConfig(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.CacheConfig {
	return predicate.CacheConfig(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.CacheConfig {
	return predicate.CacheConfig(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.CacheConfig {
	return predicate.CacheConfig(sql.FieldLTE(FieldID, id))
}

// ProviderID applies equality check predicate on the "provider_id" field. It's identical to ProviderIDEQ.
func ProviderID(v uuid.UUID) predicate.CacheConfig {
	return predicate.CacheConfig(sql.FieldEQ(FieldProviderID, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.CacheConfig {
	return predicate.CacheConfig(sql.FieldEQ(FieldEnabled, v))
}

// MaxSizeBytes applies equality check predicate on the "max_size_bytes" field. It's identical to MaxSizeBytesEQ.
func MaxSizeBytes(v int64) predicate.CacheConfig {
	return predicate.CacheConfig(sql.FieldEQ(FieldMaxSizeBytes, v))
}

// TTLSeconds applies equality check predicate on the "ttl_seconds" field. It's identical to TTLSecondsEQ.
func TTLSeconds(v int) predicate.CacheConfig {
	return predicate.CacheConfig(sql.FieldEQ(FieldTTLSeconds, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CacheConfig {
	return predicate.CacheConfig(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CacheConfig {
	return predicate.CacheConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// ProviderIDEQ applies the EQ predicate on the "provider_id" field.
func ProviderIDEQ(v uuid.UUID) predicate.CacheConfig {
	return predicate.CacheConfig(sql.FieldEQ(FieldProviderID, v))
}

// ProviderIDNEQ applies the NEQ predicate on the "provider_id" field.
func ProviderIDNEQ(v uuid.UUID) predicate.CacheConfig {
	return predicate.CacheConfig(sql.FieldNEQ(FieldProviderID, v))
}

// ProviderIDIn applies the In predicate on the "provider_id" field.
func ProviderIDIn(vs ...uuid.UUID) predicate.CacheConfig {
	return predicate.CacheConfig(sql.FieldIn(FieldProviderID, vs...))
}

// ProviderIDNotIn applies the NotIn predicate on the "provider_id" field.
func ProviderIDNotIn(vs ...uuid.UUID) predicate.CacheConfig {
	return predicate.CacheConfig(sql.FieldNotIn(FieldProviderID, vs...))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.CacheConfig {
	return predicate.CacheConfig(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.CacheConfig {
	return predicate.CacheConfig(sql.FieldNEQ(FieldEnabled, v))
}

// MaxSizeBytesEQ applies the EQ predicate on the "max_size_bytes" field.
func MaxSizeBytesEQ(v int64) predicate.CacheConfig {
	return predicate.CacheConfig(sql.FieldEQ(FieldMaxSizeBytes, v))
}

// MaxSizeBytesNEQ applies the NEQ predicate on the "max_size_bytes" field.
func MaxSizeBytesNEQ(v int64) predicate.CacheConfig {
	return predicate.CacheConfig(sql.FieldNEQ(FieldMaxSizeBytes, v))
}

// MaxSizeBytesIn applies the In predicate on the "max_size_bytes" field.
func MaxSizeBytesIn(vs ...int64) predicate.CacheConfig {
	return predicate.CacheConfig(sql.FieldIn(FieldMaxSizeBytes, vs...))
}

// MaxSizeBytesNotIn applies the NotIn predicate on the "max_size_bytes" field.
func MaxSizeBytesNotIn(vs ...int64) predicate.CacheConfig {
	return predicate.CacheConfig(sql.FieldNotIn(FieldMaxSizeBytes, vs...))
}

// MaxSizeBytesGT applies the GT predicate on the "max_size_bytes" field.
func MaxSizeBytesGT(v int64) predicate.CacheConfig {
	return predicate.CacheConfig(sql.FieldGT(FieldMaxSizeBytes, v))
}

// MaxSizeBytesGTE applies the GTE predicate on the "max_size_bytes" field.
func MaxSizeBytesGTE(v int64) predicate.CacheConfig {
	return predicate.CacheConfig(sql.FieldGTE(FieldMaxSizeBytes, v))
}

// MaxSizeBytesLT applies the LT predicate on the "max_size_bytes" field.
func MaxSizeBytesLT(v int64) predicate.CacheConfig {
	return predicate.CacheConfig(sql.FieldLT(FieldMaxSizeBytes, v))
}

// MaxSizeBytesLTE applies the LTE predicate on the "max_size_bytes" field.
func MaxSizeBytesLTE(v int64) predicate.CacheConfig {
	return predicate.CacheConfig(sql.FieldLTE(FieldMaxSizeBytes, v))
}

// TTLSecondsEQ applies the EQ predicate on the "ttl_seconds" field.
func TTLSecondsEQ(v int) predicate.CacheConfig {
	return predicate.CacheConfig(sql.FieldEQ(FieldTTLSeconds, v))
}

// TTLSecondsNEQ applies the NEQ predicate on the "ttl_seconds" field.
func TTLSecondsNEQ(v int) predicate.CacheConfig {
	return predicate.CacheConfig(sql.FieldNEQ(FieldTTLSeconds, v))
}

// TTLSecondsIn applies the In predicate on the "ttl_seconds" field.
func TTLSecondsIn(vs ...int) predicate.CacheConfig {
	return predicate.CacheConfig(sql.FieldIn(FieldTTLSeconds, vs...))
}

// TTLSecondsNotIn applies the NotIn predicate on the "ttl_seconds" field.
func TTLSecondsNotIn(vs ...int) predicate.CacheConfig {
	return predicate.CacheConfig(sql.FieldNotIn(FieldTTLSeconds, vs...))
}

// TTLSecondsGT applies the GT predicate on the "ttl_seconds" field.
func TTLSecondsGT(v int) predicate.CacheConfig {
	return predicate.CacheConfig(sql.FieldGT(FieldTTLSeconds, v))
}

// TTLSecondsGTE applies the GTE predicate on the "ttl_seconds" field.
func TTLSecondsGTE(v int) predicate.CacheConfig {
	return predicate.CacheConfig(sql.FieldGTE(FieldTTLSeconds, v))
}

// TTLSecondsLT applies the LT predicate on the "ttl_seconds" field.
func TTLSecondsLT(v int) predicate.CacheConfig {
	return predicate.CacheConfig(sql.FieldLT(FieldTTLSeconds, v))
}

// TTLSecondsLTE applies the LTE predicate on the "ttl_seconds" field.
func TTLSecondsLTE(v int) predicate.CacheConfig {
	return predicate.CacheConfig(sql.FieldLTE(FieldTTLSeconds, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CacheConfig {
	return predicate.CacheConfig(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CacheConfig {
	return predicate.CacheConfig(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CacheConfig {
	return predicate.CacheConfig(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CacheConfig {
	return predicate.CacheConfig(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CacheConfig {
	return predicate.CacheConfig(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CacheConfig {
	return predicate.CacheConfig(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CacheConfig {
	return predicate.CacheConfig(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CacheConfig {
	return predicate.CacheConfig(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CacheConfig {
	return predicate.CacheConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CacheConfig {
	return predicate.CacheConfig(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CacheConfig {
	return predicate.CacheConfig(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CacheConfig {
	return predicate.CacheConfig(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CacheConfig {
	return predicate.CacheConfig(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CacheConfig {
	return predicate.CacheConfig(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CacheConfig {
	return predicate.CacheConfig(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CacheConfig {
	return predicate.CacheConfig(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasProvider applies the HasEdge predicate on the "provider" edge.
func HasProvider() predicate.CacheConfig {
	return predicate.CacheConfig(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, ProviderTable, ProviderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProviderWith applies the HasEdge predicate on the "provider" edge with a given conditions (other predicates).
func HasProviderWith(preds ...predicate.Provider) predicate.CacheConfig {
	return predicate.CacheConfig(func(s *sql.Selector) {
		step := newProviderStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CacheConfig) predicate.CacheConfig {
	return predicate.CacheConfig(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CacheConfig) predicate.CacheConfig {
	return predicate.CacheConfig(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CacheConfig) predicate.CacheConfig {
	return predicate.CacheConfig(sql.NotPredicates(p))
}
