// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"time"

	"github.com/google/uuid"
)

type AuthPayload struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
	User         *User  `json:"user"`
}

type CreateWorkspaceInput struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

type Mutation struct {
}

type Query struct {
}

type Role struct {
	ID       uuid.UUID `json:"id"`
	Name     string    `json:"name"`
	IsSystem bool      `json:"isSystem"`
}

type Session struct {
	ID        uuid.UUID `json:"id"`
	IPAddress *string   `json:"ipAddress,omitempty"`
	UserAgent *string   `json:"userAgent,omitempty"`
	CreatedAt time.Time `json:"createdAt"`
	ExpiresAt time.Time `json:"expiresAt"`
}

type SignInInput struct {
	Email         string  `json:"email"`
	Password      string  `json:"password"`
	WorkspaceSlug *string `json:"workspaceSlug,omitempty"`
}

type SignUpInput struct {
	Email    string `json:"email"`
	Name     string `json:"name"`
	Password string `json:"password"`
}

type UpdateWorkspaceInput struct {
	Name *string `json:"name,omitempty"`
}

type User struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"createdAt"`
}

type Workspace struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	CreatedAt time.Time          `json:"createdAt"`
	Members   []*WorkspaceMember `json:"members"`
	Roles     []*Role            `json:"roles"`
}

type WorkspaceMember struct {
	ID       uuid.UUID `json:"id"`
	User     *User     `json:"user"`
	Role     *Role     `json:"role"`
	JoinedAt time.Time `json:"joinedAt"`
}
