name: Telegram Star Notification

on:
  watch:
    types: [started]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            🌟 New GitHub Star! 🌟

            Repository: ${{ github.repository }}
            Starred by: ${{ github.actor }}

            Total stars: ${{ github.event.repository.stargazers_count }}
